### ISSUE TITLE
Appium hangs after prolonged inspector use - iOS

### ISSUE THREAD

**Issue by TFry** [appium/appium-dot-app#331]
I was using Appium to inspect elements for about an hour when Appium became unresponsive. I was shown the Mac "pinwheel" when hovering over the Appium window, I waited about 15 minutes for the app to respond with no luck.

Upon attempting to close the app via OSX dock the program crashed.

Appium is up to date
OSX is up to date.
iOS version 7.1

I can post the console report if needed.

(Migrated from Appium/Appium) Thanks!

**Comment by penguinho** [comment]
This was probably caused by the max log length
