### ISSUE TITLE
Appium Doctor not running iOS/Android checks

### ISSUE THREAD

**Issue by alivetocode** [appium/appium-dot-app#374]
Appium Doctor feature is not running the iOS/Android checks...instead I get the following:

http://screencast.com/t/ci33X2Nx

Note this feature has been working fine...the only thing I can think of is I recently upgraded to v 1.2.1 but cannot be sure this is related.

The server still starts OK, and I am able to run my tests.

**Comment by penguinho** [comment]
We can keep this fix for now, it's seems like the simplest solution
