### ISSUE TITLE
Add Support for Saving and Opening Configurations

### ISSUE THREAD

**Issue by edgy360** [appium/appium-dot-app#380]
I am interested in looking into this for two reasons:
* It will make it easier when switching between multiple apps.
* It allows portability of configuration (i.e. not having to screenshot the settings to re-enter them on another Mac or Windows machine).

I am thinking that it could use a standard JSON format, containing the arguments and any other Appium GUI specific preferences.

Example:
```
{
   "args":
   {
      "address": "10.10.1.20",
      "port": 4723
   },
   "gui":
   {
      "force_scroll": true,
      "check_updates": false
   }
}
```

I am going to start working on this tonight for the OS X version, but the format of the file and structure of it is open to be changed.

**Comment by penguinho** [comment]
Appium stores all config in a plist you can probably just use the one that saved in ~/Library/Preferences for this.
