### ISSUE TITLE
Appium.app fails to launch appium server

### ISSUE THREAD

**Issue by banks** [appium/appium-dot-app#381]
As reported: https://discuss.appium.io/t/appium-app-fails-to-launch-with-no-error-messages/173

Since reporting that at least one other colleague has also reported same thing so I'm surprised there is not already an issue open that seems to descibe this. So far no one I know has managed to actually have Appium.app work out of the box.

---

Hi starting to build a test suite based on Appium. My initial enthusiasm was tempered slightly by the fact that Appium.app on OS X doesn't appear to work for me.

I found no similar comments so it must not be a common issue.

I can configure either iOS or android app as required but hitting "Launch" never does anything. It flickers the text for a few milliseconds then switches back to "Launch". No log output in the app, no Log file created (after setting "log to file" preference on).

If I try to start inspector session I just get error "no server running or no app specified" (paraphrased). If I try the doctor button also nothing happens although I see in Console.app it attempts to connect to localhost:4273 and fails.

I have actually installed appium via NPM too and managed to run programatic tests with it.

I've even managed to get the inspector working in Appium.app by manually running appium --app /path/to/android.apk externally and then running it. But that is very cumbersome an unhelpful.

I've tried every setting I thought might help - setting external node and appium binaries etc. Nothing seems to and I can't find any logs or error messages anywhere to help debug.

I've uninstalled and reinstalled the app several times, I've tried previous version (1.2.1). The version installed now is the 1.2.2 binary from Appium.io. I'm on Mavericks too if that helps.

Anyone else had this issue? If not, does anyone have some insight into how I might figure out what is going on?

Thanks for the hard work on this project, it's looking very promising.

Paul

**Comment by penguinho** [comment]
Any update here?

**Comment by RTHRELKELD1980** [comment]
I ran into this same issue. In my case Developer Settings->User External Appium Package got checked (not sure how this happened) and set to an invalid local path. I unchecked it and everything started working again.

**Comment by penguinho** [comment]
great, I'll close this then
