### ISSUE TITLE
1.2.2 :: Android: Inspector detects wrong UI hierarchy 

### ISSUE THREAD

**Issue by p00j4** [appium/appium-dot-app#388]
Having a calendar opens up [shown in screenshot], where the editText is not tappable or editable.
I drilled down the issue, if I tap it myself & as the keypad comes up, then onwards it it starts working. 
And look @ the screenshot- the NumberPicker is detected @ the wrong place [I feel thats the ideal reason for this issue because] 
![image](https://cloud.githubusercontent.com/assets/6470509/4441185/77d6657c-47cf-11e4-8767-57ca2662abce.png)

[Strangely, this issues happens randomly [very few time it works fine without any changes (those time when the inspector detects the editText properly) ]
Also the xpath is recognised for month/date/year & sending keys doesn't fail because its found in page source [ but can't see it actually happening as if its hidden or something like that ]
Attached the UiAutomator snapshot too for more clarity

![image](https://cloud.githubusercontent.com/assets/6470509/4441192/88a4db2c-47cf-11e4-99f9-196ba0a87da5.png)

I'm not sure its the issue @server level or in dot app [because problems seems to be @ both ends - ]

**Comment by edgy360** [comment]
@p00j4, and this issue too, is it the same issue as described in https://github.com/appium/appium-dot-app/issues/409?

**Comment by p00j4** [comment]
@edgy360 : I must say, you have got one of the best eye to find these issues,
well, my bad! I should have updated this issue earlier. Yes it is, and now I can recall the exact reason and solution for it, i'm gonna share it on #409 followed by closing it. Thanks.

**Comment by p00j4** [comment]
solution posted on https://github.com/appium/appium-dot-app/issues/409

**Comment by edgy360** [comment]
No problem - thanks for updating. :smile:
