### ISSUE TITLE
cannot start up mobile safari inspector with appium 1.3.1

### ISSUE THREAD

**Issue by jz5386** [appium/appium-dot-app#405]
Hi, I'm new to Appium and trying to set up mobile web app testing framework with appium. I installed appium 1.3.1 and was able to successfully get a iphone 6 siumulator up and running using 'appium &' command line (Xcode 6.1).  But I'm running into problems when trying to open up inspector from appium GUI. 

Any suggestions or help would be greatly appreciated.

1. iOS settings: it doesn't look like it's recognizing Platform Version 8.*, only 7.* selections are available. 
    I worked around this by setting flag (Thanks to Seb's help):
XXXX$ node . --device-name 'iPhone 6' --platform-name iOS --platform-version 8.1 --pre-launch --browser-name Safari

module.js:340
    throw err;
          ^
Error: Cannot find module '/Applications/Appium.app/Contents/Resources'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

2. although there are errors, it did allow 8.1 to show up in the platform version drop down window. But the simulator crashes when trying to open inspector window.
info: Welcome to Appium v1.3.1 (REV 1160ce02bb89c354cb99317985123acf39f0e7d3)

info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"safari":true,"deviceName":"iPhone 6","browserName":"Safari","showSimulatorLog":true,"defaultCommandTimeout":7200,"isolateSimDevice":true}
warn: Deprecated server args: {"--show-sim-log":"use instead: --show-ios-log"}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"}}}

info: <-- GET /wd/hub/status 200 5.475 ms - 104 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"}}}

info: <-- GET /wd/hub/status 200 1.657 ms - 104 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"}}}

info: --> GET /wd/hub/sessions {}

info: [debug] Responding to client with success: {"status":0,"value":[]}

info: <-- GET /wd/hub/sessions 200 1.361 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 6"}}

info: Client User-Agent string: Appium (unknown version) CFNetwork/673.5 Darwin/13.4.0 (x86_64) (MacBookPro8%2C2)
info: [debug] Configuring Safari session
info: [debug] We're on iOS8+ so not copying mobile safari app
info: [debug] Creating new appium session 79f21e56-c74d-4593-965b-31e1c1032c81

info: [debug] Removing any remaining instruments sockets

info: [debug] Cleaned up instruments socket /tmp/instruments_sock

info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.1

info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] iOS sim UDID is 0376ECDA-E4B3-4291-BC51-AE5D69BB4156
info: [debug] Detecting automation tracetemplate

info: [debug] Not auto-detecting udid, running on sim
info: [debug] Localizable.strings is not currently supported when using real devices.
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/yunzhu/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/yunzhu/Library/Application Support/appium/bootstrap/bootstrap-60f23230385b0cfa.js
info: [debug] Reusing dynamic bootstrap: /Users/yunzhu/Library/Application Support/appium/bootstrap/bootstrap-60f23230385b0cfa.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] Not setting device type since we're using bundle ID and assuming app is already installed
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons

info: [debug] Cleaning sim data files
info: [debug] Executing: xcrun simctl erase 0376ECDA-E4B3-4291-BC51-AE5D69BB4156

info: [debug] Cleaning mobile safari data files

warn: Applications directory /Users/yunzhu/Library/Developer/CoreSimulator/Devices/0376ECDA-E4B3-4291-BC51-AE5D69BB4156/data/Containers/Data/Application doesn't exist. Have you run this simulator before?

info: [debug] Deleting /Users/yunzhu/Library/Developer/CoreSimulator/Devices/0376ECDA-E4B3-4291-BC51-AE5D69BB4156/data/Library/Caches/Snapshots/com.apple.mobilesafari
info: [debug] Deleting /Users/yunzhu/Library/Developer/CoreSimulator/Devices/0376ECDA-E4B3-4291-BC51-AE5D69BB4156/data/Library/Caches/com.apple.mobilesafari/Cache.db*
info: [debug] Deleting /Users/yunzhu/Library/Developer/CoreSimulator/Devices/0376ECDA-E4B3-4291-BC51-AE5D69BB4156/data/Library/Caches/com.apple.WebAppCache/*.db
info: [debug] Deleting /Users/yunzhu/Library/Developer/CoreSimulator/Devices/0376ECDA-E4B3-4291-BC51-AE5D69BB4156/data/Library/Safari/*.plist
info: [debug] Deleting /Users/yunzhu/Library/Developer/CoreSimulator/Devices/0376ECDA-E4B3-4291-BC51-AE5D69BB4156/data/Library/WebKit/LocalStorage/*.*

info: [debug] Deleting /Users/yunzhu/Library/Developer/CoreSimulator/Devices/0376ECDA-E4B3-4291-BC51-AE5D69BB4156/data/Library/WebKit/GeolocationSites.plist
info: [debug] Deleting /Users/yunzhu/Library/Developer/CoreSimulator/Devices/0376ECDA-E4B3-4291-BC51-AE5D69BB4156/data/Library/Cookies/*.binarycookies
info: [debug] Isolating the requested simulator by deleting all others
info: [debug] Executing: xcrun simctl list devices

info: [debug] Executing: xcrun simctl delete Shutdown

info: [debug] Cleaning up appium session

info: [debug] Error: Command failed: Invalid device: Shutdown

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

error: Failed to start an Appium session, err was: Error: Command failed: Invalid device: Shutdown

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: Invalid device: Shutdown\n)","killed":false,"code":145,"signal":null,"origValue":"Command failed: Invalid device: Shutdown\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 1542.592 ms - 246 

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"}}}
info: <-- GET /wd/hub/status 200 1.600 ms - 104 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"}}}
info: <-- GET /wd/hub/status 200 1.029 ms - 104 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"}}}

**Comment by edgy360** [comment]
@jz5386, are you still experiencing this issue?

**Comment by jz5386** [comment]
I was able to get it working after install my mac completely. 

thank you for following up.

Julie

**Comment by edgy360** [comment]
Good to hear - thanks!
