### ISSUE TITLE
Appium GUI server will not start if changing directory

### ISSUE THREAD

**Issue by shlomitc** [appium/appium-dot-app#417]
In my `~/.bash_profile` file I had the following command: `cd ~/someFolder`.
This caused Appium GUI server to not start.
Once I click "Launch", it changes to "Stop" and immediately back to "Launch", without showing any logs or errors.
After being aggressive with appium and clicking multiple times on 'Launch' button, I got the following error:

    Error: Cannot find module 'Users/shlomitc/someFolder/lib/server/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

That's when it hit me that the cause was changing the bash_profile.

**Comment by edgy360** [comment]
This should be fixed in the next release of Appium.app. Please reopen the issue if you find that it doesn't work.

The way I tested this was by adding `cd ~/Desktop` to the top of my `.bash_profile`.
