### ISSUE TITLE
I/O Exception when logTextView reaches the max length

### ISSUE THREAD

**Issue by hsoochun** [appium/appium-dot-app#421]
When you are running a massive test and the log (logTextView) reaches the max length,
I/O Exception happens and test is hanging

INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:4723: The target server failed to respond

The workaround of this is clearing the log, but it takes very long if you try to clear the log.

The app should have an option or by default clear the log automatically when the log reaches to a specific length.

**Comment by edgy360** [comment]
Thanks for reporting this issue @hsoochun. It should be fixed in the next release of Appium.app. Please reopen this issue if the problem still appears.
