### ISSUE TITLE
Unable to Get Elements in the Appium inspector when clicking on the app screen.

### ISSUE THREAD

**Issue by Rakeshvallabhaneni** [appium/appium-dot-app#423]
@bootstraponline @penguinho @jlipps

unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)"

Hi i AM USING APPIUM 1.3.3 MY App is Native but from past two days i am facing a problem to get elements from Appium inspector ,please find below appium LOG ... I tried all ways my iOS version is 8.1.2 i am getting the app screen in inspector but when clicking on the screen in the inspector NO response .

iOS : 8.1.2
Xcode:6.1.1
App : Native 

Note : Before it use to work perfect but since two days its not working.

info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to 999999 secs
info: [debug] Appium session started with sessionId 7c3650b3-d23d-467f-95ec-7b54ba31eb37
info: <-- POST /wd/hub/session 303 12541.382 ms - 9

info: --> GET /wd/hub/session/7c3650b3-d23d-467f-95ec-7b54ba31eb37 {}
info: [debug] Responding to client with success: {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iOS","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"platformName":"iOS","platformVersion":"7.1.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"Cigi"},"platformName":"iOS","platformVersion":"7.1.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"Cig"},"sessionId":"7c3650b3-d23d-467f-95ec-7b54ba31eb37"}
info: <-- GET /wd/hub/session/7c3650b3-d23d-467f-95ec-7b54ba31eb37 200 1.502 ms - 548 {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iOS","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"platformName":"iOS","platformVersion":"7.1.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"Cig"},"platformName":"iOS","platformVersion":"7.1.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"Cig"},"sessionId":"7c3650b3-d23d-467f-95ec-7b54ba31eb37"}

info: --> GET /wd/hub/session/7c3650b3-d23d-467f-95ec-7b54ba31eb37/source {}

info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-01-02 04:40:43 +0000 Debug: Got new command 3 from instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-01-02 04:40:43 +0000 Debug: evaluating au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-01-02 04:40:44 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-01-02 04:40:44 +0000 Debug: responding with:valid":true,"visible":true,"hint":null,"path":"/0/0","x":0,"y":0,"width":320,"height":568},">":[{"UIANavigationBar":{"@":{"name":"ESI Ditto Login","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0","x":0,"y":20,"width":320,"height":44},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/0","x":0,"y":0,"width":320,"height":64},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/0/0","x":0,"y":64,"width":320,"height":0.5},">":[]}}]}},{"UIAButton":{"@":{"name":"Cancel","label":"Cancel","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0/1","x":8,"y":28,"width":54,"height":30},">":[]}},{"UIAButton":{"@":{"name":"Back","label":"Back","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/2","x":8,"y":31.5,"width":21,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"ESI Ditto Login","label":"ESI Ditto Login","value":"ESI Ditto Login","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0/3","x":101,"y":28,"width":118,"height":27},">":[]}},{"UIAButton":{"@":{"name":"Login","label":"Login","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0/4","x":269,"y":28,"width":43,"height":30},">":[]}}]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/1","x":94.5,"y":72,"width":131,"height":100},">":[]}},{"UIATableView":{"@":{"name":null,"label":null,"value":"rows 1 to 4 of 4","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/2","x":20,"y":172,"width":280,"height":336},">":[{"UIATableCell":{"@":{"name":null,"label":null,"value":"","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/2/0","x":20,"y":207,"width":280,"height":44},">":[{"UIATextField":{"@":{"name":null,"label":"","value":": ","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/2/0/0","x":35,"y":207,"width":320,"height":44},">":[]}}]}},{"UIATableCell":{"@":{"name":null,"label":null,"value":"","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/2/1","x":20,"y":251,"width":280,"height":44},">":[{"UIATextField":{"@":{"name":null,"label":"","value":"extension@domainname","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/2/1/0","x":35,"y":251,"width":320,"height":44},">":[]}}]}},{"UIATableCell":{"@":{"name":null,"label":null,"value":"","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/2/2","x":20,"y":295,"width":280,"height":44},">":[{"UIASecureTextField":{"@":{"name":null,"label":"","value":"password","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/2/2/0","x":35,"y":295,"width":320,"height":44},">":[]}}]}},{"UIATableCell":{"@":{"name":"Server:","label":null,"value":"","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/2/3","x":20,"y":374,"width":280,"height":44},">":[{"UIAStaticText":{"@":{"name":"Server:","label":"Server:","value":"Server:","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/2/3/0","x":35,"y":386,"width":54.5,"height":20.5},">":[]}},{"UIAStaticText":{"@":{"name":"Cloud PBX","label":"Cloud PBX","value":"Cloud PBX","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/2/3/1","x":181,"y":386,"width":84,"height":20.5},">":[]}}]}}]}},{"UIAStaticText":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/3","x":0,"y":508,"width":320,"height":50},">":[]}},{"UIAActivityIndicator":{"@":{"name":"Progress halted","label":"Progress halted","value":"
0","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/4","x":150,"y":511,"width":20,"height":20},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/4/0","x":150,"y":511,"width":20,"height":20},">":[]}}]}},{"UIAToolbar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/5","x":0,"y":568,"width":320,"height":44},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/5/0","x":0,"y":567.5,"width":320,"height":0.5},">":[]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/5/1","x":0,"y":568,"width":320,"height":44},">":[]}}]}}]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/1","x":0,"y":0,"width":320,"height":568},">":[]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/2","x":0,"y":0,"width":320,"height":568},">":[{"UIAStatusBar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/2/0","x":0,"y":0,"width":320,"height":20},">":[{"UIAElement":{"@":{"name":"5 of 5 bars, signal strength","label":"5 of 5 bars, signal strength","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/0","x":6,"y":0,"width":35,"height":20},">":[]}},{"UIAElement":{"@":{"name":"\u0001airtel network","label":"\u0001airtel network","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/1","x":44,"y":0,"width":28,"height":20},">":[]}},{"UIAElement":{"@":{"name":"3G","label":"3G","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/2","x":81,"y":0,"width":17,"height":20},">":[]}},{"UIAElement":{"@":{"name":"10:10 am","label":"10:10 am","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/3","x":136,"y":0,"width":49,"height":20},">":[]}},{"UIAElement":{"@":{"name":"81% battery power, Charging","label":"81% battery power, Charging","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/4","x":255,"y":0,"width":60,"height":20},">":[]}}]}}]}}]}}}
2015-01-02 04:40:44 +0000 Debug: Running system command #4: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"ESIDitto","label":"ESIDitto","value":null,"dom"...

info: [debug] Socket data received (7603 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"ESIDitto","label":"ESIDitto","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":20,"width":320,"height":548},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"

info: [debug] Responding to client with success: {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n \n \n \n \n \n \n \n <UIAButton name=\"Cancel\" label=\"Ca...","sessionId":"7c3650b3-d23d-467f-95ec-7b54ba31eb37"}

info: <-- GET /wd/hub/session/7c3650b3-d23d-467f-95ec-7b54ba31eb37/source 200 1089.994 ms - 8993 {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n \n \n \n \n \n \n \n info: --> GET /wd/hub/session/7c3650b3-d23d-467f-95ec-7b54ba31eb37/orientation {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] Sending command to instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-01-02 04:40:45 +0000 Debug: Got new command 4 from instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-01-02 04:40:45 +0000 Debug: evaluating au.getScreenOrientation()

info: [debug] [INST] 2015-01-02 04:40:45 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-01-02 04:40:45 +0000 Debug: responding with:
info: [debug] [INST] 2015-01-02 04:40:45 +0000 Debug: Running system command #5: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...

info: [debug] Socket data received (33 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Setting internal orientation to PORTRAIT
info: [debug] Responding to client with success: {"status":0,"value":"PORTRAIT","sessionId":"7c3650b3-d23d-467f-95ec-7b54ba31eb37"}

info: <-- GET /wd/hub/session/7c3650b3-d23d-467f-95ec-7b54ba31eb37/orientation 200 957.927 ms - 82 {"status":0,"value":"PORTRAIT","sessionId":"7c3650b3-d23d-467f-95ec-7b54ba31eb37"}
info: --> GET /wd/hub/session/7c3650b3-d23d-467f-95ec-7b54ba31eb37/screenshot {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] Sending command to instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-01-02 04:40:46 +0000 Debug: Got new command 5 from instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-01-02 04:40:46 +0000 Debug: evaluating au.getScreenOrientation()

info: [debug] Socket data received (33 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Setting internal orientation to PORTRAIT
info: [debug] Pushing command to appium work queue: "au.capture('screenshotf7a4e2e3-562c-450f-ab05-4537437a9375')"
info: [debug] Sending command to instruments: au.capture('screenshotf7a4e2e3-562c-450f-ab05-4537437a9375')

info: [debug] [INST] 2015-01-02 04:40:46 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-01-02 04:40:46 +0000 Debug: responding with:

info: [debug] [INST] 2015-01-02 04:40:46 +0000 Debug: Running system command #6: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...

info: [debug] [INST] 2015-01-02 04:40:47 +0000 Debug: Got new command 6 from instruments: au.capture('screenshotf7a4e2e3-562c-450f-ab05-4537437a9375')

info: [debug] [INST] 2015-01-02 04:40:47 +0000 Debug: evaluating au.capture('screenshotf7a4e2e3-562c-450f-ab05-4537437a9375')

info: [debug] Socket data received (25 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}

info: [debug] [INST] 2015-01-02 04:40:47 +0000 Debug: target.captureRectOnScreenWithName("{origin:{x:0.00,y:0.00}, size:{height:568.00,width:320.00}}", UIScreen, "screenshotf7a4e2e3-562c-450f-ab05-4537437a9375")

info: [debug] [INST] 2015-01-02 04:40:47 +0000 Screenshot captured.

info: [debug] [INST] 2015-01-02 04:40:47 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-01-02 04:40:47 +0000 Debug: responding with:
info: [debug] [INST] 2015-01-02 04:40:47 +0000 Debug: Running system command #7: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

info: [debug] Responding to client with success: {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAoAAAARwCAYAAAB6j+UAAAAKQWlDQ1BJQ0MgUHJvZmlsZQAASA2dlndUU9kWh8+9N73QEiIgJfQaegkg0jtIFQRRiUmAUAKGhCZ2RAVGFBEpVmRUwAFHhyJjRRQLg4Ji1wnyEFDGwVFEReXdjGsJ7601896a/cdZ39nnt9fZZ+9917oAUPyCBMJ0WAGANKFYFO7rwVwSE8vE9wIYEAEOWAHA4WZmBEf4RALU/L09mZmoSMaz9u4ugGS72yy/UCZz1v9/kSI3QyQGAApF1TY8fiYX5QKUU7PFGTL/BMr0lSkyhjEyFqEJoqwi48SvbPan5iu7yZiXJuShGlnOGbw0noy7UN6aJeGjjAShXJgl4GejfAdlvVRJmgDl9yjT0/icTAAwFJlfzOcmoWyJMkUUGe6J8gIACJTEObxyDov5OWieAHimZ+SKBIlJYqYR15hp5ejIZvrxs1P5YjErlMNN4Yh4TM/0tAyOMBeAr2+WRQElWW2ZaJHtrRzt7VnW5mj5v9nfHn5T/T3IevtV8Sbsz55BjJ5Z32zsrC+9FgD2JFqbHbO+lVUAtG0GQOXhrE/vIADyBQC03pzzHoZsXpLE4gwnC4vs7GxzAZ9rLivoN/ufgm/Kv4Y595nL7vtWO6YXP4EjSRUzZUXlpqemS0TMzAwOl89k/fcQ/+PAOWnNycMsnJ/AF/GF6FVR6JQJhIlou4U8gViQLmQKhH/V4X8YNicHGX6daxRodV8AfYU5ULhJB8hvPQBDIwMkbj96An3rWxAxCsi+vGitka9zjzJ6/uf6Hwtcim7hTEEiU+b2DI9kciWiLBmj34RswQISkAd0oAo0gS4wAixgDRyAM3AD3iAAhIBIEAOWAy5IAmlABLJBPtgACkEx2AF2g2pwANSBetAEToI2cAZcBFfADXALDIBHQAqGwUswAd6BaQiC8BAVokGqkBakD5lC1hAbWgh5Q0FQOBQDxUOJkBCS...","sessionId":"7c3650b3-d23d-467f-95ec-7b54ba31eb37"}

info: <-- GET /wd/hub/session/7c3650b3-d23d-467f-95ec-7b54ba31eb37/screenshot 200 2379.324 ms - 92190 {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAoAAAARwCAYAAAB6j+UAAAAKQWlDQ1BJQ0MgUHJvZmlsZQAASA2dlndUU9kWh8+9N73QEiIgJfQaegkg0jtIFQRRiUmAUAKGhCZ2RAVGFBEpVmRUwAFHhyJjRRQLg4Ji1wnyEFDGwVFEReXdjGsJ7601896a/cdZ39nnt9fZZ+9917oAUPyCBMJ0WAGANKFYFO7rwVwSE8vE9wIYEAEOWAHA4WZmBEf4RALU/L09mZmoSMaz9u4ugGS72yy/UCZz1v9/kSI3QyQGAApF1TY8fiYX5QKUU7PFGTL/BMr0lSkyhjEyFqEJoqwi48SvbPan5iu7yZiXJuShGlnOGbw0noy7UN6aJeGjjAShXJgl4GejfAdlvVRJmgDl9yjT0/icTAAwFJlfzOcmoWyJMkUUGe6J8gIACJTEObxyDov5OWieAHimZ+SKBIlJYqYR15hp5ejIZvrxs1P5YjErlMNN4Yh4TM/0tAyOMBeAr2+WRQElWW2ZaJHtrRzt7VnW5mj5v9nfHn5T/T3IevtV8Sbsz55BjJ5Z32zsrC+9FgD2JFqbHbO+lVUAtG0GQOXhrE/vIADyBQC03pzzHoZsXpLE4gwnC4vs7GxzAZ9rLivoN/ufgm/Kv4Y595nL7vtWO6YXP4EjSRUzZUXlpqemS0TMzAwOl89k/fcQ/+PAOWnNycMsnJ/AF/GF6FVR6JQJhIlou4U8gViQLmQKhH/V4X8YNicHGX6daxRodV8AfYU5ULhJB8hvPQBDIwMkbj96An3rWxAxCsi+vGitka9zjzJ6/uf6Hwtcim7hTEEiU+b2DI9kciWiLBmj34RswQISkAd0oAo0gS4wAixgDRyAM3AD3iAAhIBIEAOWAy5IAmlABLJBPtgACkEx2AF2g2pwANSBetAEToI2cAZcBFfADXALDIBHQAqGwUswAd6BaQiC8BAVokGqkBakD5lC1hAbWgh5Q0FQOBQDxUOJkBCS...","sessionId":"7c3650b3-d23d-467f-95ec-7b54ba31eb37"}

info: --> GET /wd/hub/session/7c3650b3-d23d-467f-95ec-7b54ba31eb37/contexts {}

error: [REMOTE] Could not connect to WebKitRemoteDebugger server

info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"7c3650b3-d23d-467f-95ec-7b54ba31eb37"}
info: <-- GET /wd/hub/session/7c3650b3-d23d-467f-95ec-7b54ba31eb37/contexts 500 8.010 ms - 293

info: --> GET /wd/hub/status {}

Thanks ,
Rakeshkumar

**Comment by edgy360** [comment]
Please could you confirm if this issue is the same as described in https://github.com/appium/appium-dot-app/issues/409?

**Comment by Rakeshvallabhaneni** [comment]
No @edgy360 

Even i am facing the issue  with 1.3.3  in two ways ...

1) If the app(Native) already installed in the device .and i click on inspector button in the appium here i am able to launch the app and screen shot also showing in the inspetor but unable to locate element in that.

error: [REMOTE] Could not connect to WebKitRemoteDebugger server

info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"834ca544-77f4-498f-8232-0a4f788e9dca"}
info: <-- GET /wd/hub/session/834ca544-77f4-498f-8232-0a4f788e9dca/contexts 500 7.407 ms - 293


2)If the app is not installed in the device when i click on inspector it should install and launch but

error: Failed to start an Appium session, err was: Error: Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.
]

info: [debug] Error: Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.
]
at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/common.js:147:10
at ChildProcess.exithandler (child_process.js:652:7)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:756:16)
at Socket. (child_process.js:969:11)
at Socket.emit (events.js:95:17)
at Pipe.close (net.js:465:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.\n])","origValue":"Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.\n]"},"sessionId":null}

info: <-- POST /wd/hub/session 500 7046.653 ms - 578

Please help me around these problem.

Thanks.

**Comment by edgy360** [comment]
Sorry for the delay in responding to your comment. This looks to be a server side issue. Please raise it on the main Appium repository issues if you haven't already: https://github.com/appium/appium/issues
