### ISSUE TITLE
Cpu/Memory issue when too many log line.

### ISSUE THREAD

**Issue by sebv** [appium/appium-dot-app#426]
See https://github.com/appium/appium/issues/4279 (this does not look related to iPad).

```
Appium GUI hangs when the test runs for about an hour(CPU utilization of appiun GUI goes upto 100%).After running for about an hour, not able to open the appium UI itself.

The issue is not happening when clicked on 'Clear Log' in appium GUI.
```

**Comment by edgy360** [comment]
Linked to https://github.com/appium/appium-dot-app/issues/421.

**Comment by edgy360** [comment]
Hi @vasudarch, this should be fixed in the next release of Appium.app. Please reopen this issue if the problem still appears.

**Comment by vasudarch** [comment]
Thanks edgy360 for fixing this issue

**Comment by edgy360** [comment]
That isn't a problem. Please let us know if the issue still appears in the next release and then we can fix any additional causes of this problem.=
