### ISSUE TITLE
Selenium Error: 6 - Error Domain=com.appium.selenium Code=6 "NoSuchDriver: A session is either terminated or not started." UserInfo=0x608000a7cc40 {NSLocalizedDescription=NoSuchDriver: A session is either terminated or not started.}

### ISSUE THREAD

**Issue by vascon8** [appium/appium-dot-app#427]
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.AndroidCommandExecutor.execute(AndroidCommandExecutor.java:64)

info: [debug] [UIAUTOMATOR STDOUT] at

info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.SocketServer.runCommand(SocketServer.java:168)
info: [debug] [UIAUTOMATOR STDOUT] at io.appium.android.bootstrap.SocketServer.handleClientData(SocketServer.java:89)
info: [debug] [UIAUTOMATOR STDOUT] at io.appium.android.bootstrap.SocketServer.listenForever(SocketServer.java:133)
info: [debug] [UIAUTOMATOR STDOUT] at io.appium.android.bootstrap.Bootstrap.testRunServer(Bootstrap.java:16)
info: [debug] [UIAUTOMATOR STDOUT] at

info: [debug] [UIAUTOMATOR STDOUT] java.lang.reflect.Method.invokeNative(Native Method)
info: [debug] [UIAUTOMATOR STDOUT] at
info: [debug] [UIAUTOMATOR STDOUT] java.lang.reflect.Method.invoke(Method.java:511)
info: [debug] [UIAUTOMATOR STDOUT] at
info: [debug] [UIAUTOMATOR STDOUT] junit.framework.TestCase.runTest(TestCase.java:168)
info: [debug] [UIAUTOMATOR STDOUT] at
info: [debug] [UIAUTOMATOR STDOUT] junit.framework.TestCase.runBare(TestCase.java:134)
info: [debug] [UIAUTOMATOR STDOUT] at

info: [debug] [UIAUTOMATOR STDOUT] junit.framework.TestResult$1.protect(TestResult.java:115)

info: [debug] [UIAUTOMATOR STDOUT] at
info: [debug] [UIAUTOMATOR STDOUT] junit.framework.TestResult.runProtected(TestResult.java:133)
info: [debug] [UIAUTOMATOR STDOUT] at
info: [debug] [UIAUTOMATOR STDOUT] junit.framework.TestResult.run(TestResult.java:118)

info: [debug] [UIAUTOMATOR STDOUT] at

info: [debug] [UIAUTOMATOR STDOUT] junit.framework.TestCase.run(TestCase.java:124)
info: [debug] [UIAUTOMATOR STDOUT] at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:144)
info: [debug] [UIAUTOMATOR STDOUT] at
info: [debug] [UIAUTOMATOR STDOUT] com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:87)

info: [debug] [UIAUTOMATOR STDOUT] at

info: [debug] [UIAUTOMATOR STDOUT] com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:90)
info: [debug] [UIAUTOMATOR STDOUT] at
info: [debug] [UIAUTOMATOR STDOUT] com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
info: [debug] [UIAUTOMATOR STDOUT] at
info: [debug] [UIAUTOMATOR STDOUT] dalvik.system.NativeStart.main(Native Method)
info: [debug] [UIAUTOMATOR STDOUT] Caused by:
info: [debug] [UIAUTOMATOR STDOUT] libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)

info: [debug] [UIAUTOMATOR STDOUT] at
info: [debug] [UIAUTOMATOR STDOUT] libcore.io.Posix.open(Native Method)

info: [debug] [UIAUTOMATOR STDOUT] at

info: [debug] [UIAUTOMATOR STDOUT] libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)

info: [debug] [UIAUTOMATOR STDOUT] at

info: [debug] [UIAUTOMATOR STDOUT] libcore.io.IoBridge.open(IoBridge.java:400)

info: [debug] [UIAUTOMATOR STDOUT] ...

info: [debug] [UIAUTOMATOR STDOUT] 25
info: [debug] [UIAUTOMATOR STDOUT] more
info: [debug] [BOOTSTRAP] [debug] Command returned error:java.lang.RuntimeException: Failed to Dump Window Hierarchy
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Failed to Dump Window Hierarchy","status":13}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Failed to Dump Window Hierarchy"},"sessionId":"193c581e-6e34-4ad5-a2ec-80de312769fa"}
info: <-- GET /wd/hub/session/193c581e-6e34-4ad5-a2ec-80de312769fa/source 500 5309.943 ms - 200 
info: --> GET /wd/hub/session/193c581e-6e34-4ad5-a2ec-80de312769fa/orientation {}
info: [deb

**Comment by edgy360** [comment]
This looks like a server side issue. If you haven't done so already, then please raise the issue here and provide a link back to this original issue: https://github.com/appium/appium/issues
