### ISSUE TITLE
"Could not connect to WebKitRemoteDebugger server"- error received when opening inspector with a native app 

### ISSUE THREAD

**Issue by adigrinvald** [appium/appium-dot-app#428]
The Appium Inspector doesn't know whether your app does or does not have any webviews, and it tries to determine that by connecting to the remote debugger.

if the inspector doesn't find any webviews it should silently ignore this option

This was found in Appium 1.3.4 (Mac OS 10.10.1 with real device - iPhone)

**Comment by Rakeshvallabhaneni** [comment]
@bootstraponline @adigrinvald @edgy360 @admc @Astro03 @jlipps 

Even i am facing the issue with 1.3.3 in two ways ...

1) If the app(Native) already installed in the device .and i click on inspector button in the appium here i am able to launch the app and screen shot also showing in the inspetor but unable to locate element in that.

error: [REMOTE] Could not connect to WebKitRemoteDebugger server

info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"834ca544-77f4-498f-8232-0a4f788e9dca"}
info: <-- GET /wd/hub/session/834ca544-77f4-498f-8232-0a4f788e9dca/contexts 500 7.407 ms - 293

2)If the app is not installed in the device when i click on inspector it should install and launch but

error: Failed to start an Appium session, err was: Error: Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.
]

info: [debug] Error: Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.
]
at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/common.js:147:10
at ChildProcess.exithandler (child_process.js:652:7)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:756:16)
at Socket. (child_process.js:969:11)
at Socket.emit (events.js:95:17)
at Pipe.close (net.js:465:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.\n])","origValue":"Unable to install [com.esi-estech.ditto] to device with id [db683f62be2549a89f2f4a0012239a9b947da62e]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.\n]"},"sessionId":null}

info: <-- POST /wd/hub/session 500 7046.653 ms - 578

Please help me around these problem.

Thanks.

**Comment by penguinho** [comment]
Is this still happening? @Rakeshvallabhaneni @adigrinvald

**Comment by Rakeshvallabhaneni** [comment]
@penguinho 
This is not happening currently . Thank you.

**Comment by n4me1ess** [comment]
@penguinho I have reproduced the problem.
 appium v1.4.0 , used external appium package by source v 1.4.7
 the native app Native already installed in the device .and i click on inspector button in the appium here i am able to launch the app  also showing in the inspector but unable to do something with element in that(click, for example).
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
error: [REMOTE] Could not connect to WebKitRemoteDebugger server
It there any workaround?

**Comment by codedgeass** [comment]
Specifying the UDID and port number when starting the iOS Webkit Debug Proxy at the command line solved this for me.

**Comment by mi2pankaj** [comment]
Did you run tests after starting ios_webkit_debug_proxy server along with appium server, if not start it by using command: ios_webkit_debug_proxy -c <udid>:27753 -d
If you don't have ios_webkit_debug_proxy then install it by using command:  brew install ios-webkit-debug-proxy

**Comment by AmirBuchvalter** [comment]
Try to run the next command: "ios_webkit_debug_proxy" to get a proper status of your connected device and checkout the message.
In my case, which included a similar error, had been solved with the next steps: safari -> advanced -> Web inspector = ON
