### ISSUE TITLE
Appium1.3.4, element can be tapped in inspector,but can't when send tap command from script

### ISSUE THREAD

**Issue by vascon8** [appium/appium-dot-app#437]
has no scrollable ancestor.
info: [debug] [INST STDERR] 2015-01-13 22:11:00.772 ScriptAgent[3395:2e0f] Log written to /Users/xinliu/Library/Application Support/iPhone Simulator/7.1-64/Library/Logs/CrashReporter/UIALogs/ScriptError-2015-01-13-221100.plist
info: [debug] [INST] 2015-01-13 14:11:00 +0000 Debug: target.frontMostApp().elements()[0].elements()[0].elements()[0].elements()[4] - scrollToVisible cannot be used because this element has no scrollable ancestor.
info: [debug] [INST] 2015-01-13 14:11:00 +0000 Debug: target.frontMostApp().elements()[0].elements()[0].elements()[0].elements()[4] could not be tapped because the element is not visible

info: [debug] [INST] 2015-01-13 14:11:00 +0000 Error: VerboseError: elementId 1 could not be tapped

info: [debug] Socket data received (57 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":13,"value":"elementId 1 could not be tapped"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"elementId 1 could not be tapped"},"sessionId":"99befa78-2a1c-4b42-b979-ecea83c769f2"}

info: <-- POST /wd/hub/session/99befa78-2a1c-4b42-b979-ecea83c769f2/element/1/click 500 213.677 ms - 200

**Comment by vascon8** [comment]
the element can be tapped in the inspector window. but can't when run a script

**Comment by penguinho** [comment]
I'm wondering if the locator you are using is ambiguous, can you post the code you are using to find the element? Appium.app always uses xpath with inidices behind the scenes, which is unlikely to be what you are using.

**Comment by vascon8** [comment]
my script have two commands:
wd.find_element_by_xpath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIALink[1]").click()
	wd.find_element_by_xpath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIATextField[1]").click()
	


nfo: [debug] Socket data received (5323 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"0926sinaweibo","label":"0926sinaweibo","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":20,"width":320,"height":548},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabl
info: [debug] Pushing command to appium work queue: "au.getElementByIndexPath('/0/0/0/0/4')"
info: [debug] Sending command to instruments: au.getElementByIndexPath('/0/0/0/0/4')

info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: Got new command 10 from instruments: au.getElementByIndexPath('/0/0/0/0/4')
info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: evaluating au.getElementByIndexPath('/0/0/0/0/4')
info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: responding with:
info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: Running system command #11: /Users/xinliu/Library/Developer/Xcode/DerivedData/Appium-gxuqgircsntxymdkhnilrjsosnzi/Build/Products/Debug/Appium.app/Contents/Resources/node/bin/node /Users/xinliu/Library/Developer/Xcode/DerivedData/Appium-gxuqgircsntxymdkhnilrjsosnzi/Build/Products/Debug/Appium.app/Contents/Resources/node_modules...

info: [debug] Socket data received (38 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"1"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"c971888d-d7b9-48a7-82aa-df4bd8736b36"}
info: <-- POST /wd/hub/session/c971888d-d7b9-48a7-82aa-df4bd8736b36/element 200 308.964 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"c971888d-d7b9-48a7-82aa-df4bd8736b36"}
info: --> POST /wd/hub/session/c971888d-d7b9-48a7-82aa-df4bd8736b36/element/1/click {"sessionId":"c971888d-d7b9-48a7-82aa-df4bd8736b36","id":"1"}
info: [debug] Pushing command to appium work queue: "au.tapById('1')"
info: [debug] Sending command to instruments: au.tapById('1')
info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: Got new command 11 from instruments: au.tapById('1')
info: [debug] [INST STDERR] 2015-01-14 20:04:05.637 ScriptAgent[1215:2a0f] Log written to /Users/xinliu/Library/Application Support/iPhone Simulator/7.1-64/Library/Logs/CrashReporter/UIALogs/ScriptError-2015-01-14-200405.plist
info: [IOS_SYSLOG_ROW ] Jan 14 20:04:05 xindeMacBook-Pro.local ScriptAgent[1215] <Warning>: Log written to /Users/xinliu/Library/Application Support/iPhone Simulator/7.1-64/Library/Logs/CrashReporter/UIALogs/ScriptError-2015-01-14-200405.plist

info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: evaluating au.tapById('1')
info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: target.frontMostApp().elements()[0].elements()[0].elements()[0].elements()[4].tap()
info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: target.frontMostApp().elements()[0].elements()[0].elements()[0].elements()[4].scrollToVisible()
info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: target.frontMostApp().elements()[0].elements()[0].elements()[0].elements()[4] - scrollToVisible cannot be used because this element has no scrollable ancestor.
info: [debug] [INST STDERR] 2015-01-14 20:04:05.649 ScriptAgent[1215:2a0f] Log written to /Users/xinliu/Library/Application Support/iPhone Simulator/7.1-64/Library/Logs/CrashReporter/UIALogs/ScriptError-2015-01-14-200405.plist
info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: target.frontMostApp().elements()[0].elements()[0].elements()[0].elements()[4] - scrollToVisible cannot be used because this element has no scrollable ancestor.
info: [debug] [INST] 2015-01-14 12:04:05 +0000 Debug: target.frontMostApp().elements()[0].elements()[0].elements()[0].elements()[4] could not be tapped because the element is not visible

info: [debug] [INST] 2015-01-14 12:04:05 +0000 Error: VerboseError: elementId 1 could not be tapped

info: [debug] Socket data received (57 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":13,"value":"elementId 1 could not be tapped"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"elementId 1 could not be tapped"},"sessionId":"c971888d-d7b9-48a7-82aa-df4bd8736b36"}
info: <-- POST /wd/hub/session/c971888d-d7b9-48a7-82aa-df4bd8736b36/element/1/click 500 288.277 ms - 200

**Comment by penguinho** [comment]
This is likely a server issue since it is working in the application. Raise the issue on the appium server project. https://github.com/appium/appium/issues

**Comment by edgy360** [comment]
Closing due to no update. Please reopen if you find that this is a client side issue.

**Comment by mohitsdet** [comment]
any update on this as i am facing same issue
target.frontMostApp().elements()[1].elements()[13].elements()[0].elements()[0] could not be tapped[39m
[36minfo[39m: [debug] Socket data received (58 bytes)
