### ISSUE TITLE
Not able to open on 10.9.5

### ISSUE THREAD

**Issue by vikramvi** [appium/appium-dot-app#460]
Hi,
I downloaded latest version from appium website but it's not opening.

Is there any crash log file which I can share to find out issue ?

Thanks & Regards,
Vikram

**Comment by edgy360** [comment]
Is it the DMG that you cannot open?

**Comment by vikramvi** [comment]
Hi edgy360,
No it is the actual app post installing. I click on Icon and it closes without any message.

Is there any way I can look into error log ?
Thanks & Regards,
Vikram

**Comment by edgy360** [comment]
The only real error log that I can think of is looking in the system 'Console' app. Just filter the logs down by searching 'appium'.

Please could you also try downloading Appium from scratch, incase the update somehow didn't download fully?

**Comment by edgy360** [comment]
Please could you try the latest version and reopen the issue if you still cannot open Appium?
