### ISSUE TITLE
The following desired capabilities are required, but were not provided: deviceName (or)Failed to start an Appium session, err was: Error: Log capture did not start in a reasonable amount of time

### ISSUE THREAD

**Issue by RajeshDuraisamy** [appium/appium-dot-app#472]
Hi All,

I am new to Appium and I am trying to run the appium.app with iOS option using stimulator.I have selected the app path and show stimulator log with platform version as 8.1.

I have also added appium.txt file with the following content in the appium installation directory.
[caps]
platformName = "ios"
deviceName = "iPhone 6"
platformVersion = "8.1"
app = “/Users/dhanasekarbabu/downloads/untitled/UICatalog.app"

Also please find the following log,

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --platform-version "8.1" --platform-name "iOS" --app "/Users/dhanasekarbabu/Downloads/untitled/UICatalog.app" --show-ios-log --default-device

info: Welcome to Appium v1.3.6 (REV 004f52f249d3513809e7d0734d9205d1fec19f8e)

info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"app":"/Users/dhanasekarbabu/Downloads/untitled/UICatalog.app","platformName":"iOS","platformVersion":"8.1","defaultDevice":true,"showIOSLog":true,"defaultCommandTimeout":7200}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: <-- GET /wd/hub/status 200 13.582 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}
info: <-- GET /wd/hub/status 200 4.070 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}
info: --> GET /wd/hub/sessions {}
info: [debug] Responding to client with success: {"status":0,"value":[]}
info: <-- GET /wd/hub/sessions 200 1.517 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.1","newCommandTimeout":"999999","automationName":"Appium"}}

error: The following desired capabilities are required, but were not provided: deviceName

info: Client User-Agent string: Appium (unknown version) CFNetwork/720.2.4 Darwin/14.1.0 (x86_64)
info: [debug] Got configuration error, not starting session
info: [debug] Cleaning up appium session
info: [debug] Error: The following desired capabilities are required, but were not provided: deviceName
    at Capabilities.checkValidity (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/capabilities.js:143:13)
    at Appium.configure (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js:238:35)
    at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js:118:10)
    at Appium.start (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js:129:5)
    at Object.exports.createSession [as handle] (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/controller.js:182:16)
    at next_layer (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:113:13)
    at Route.dispatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/route.js:117:5)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:222:24
    at Function.proto.process_params (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:288:12)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/express/lib/router/index.js:216:19)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: The following desired capabilities are required, but were not provided: deviceName)","origValue":"The following desired capabilities are required, but were not provided: deviceName"},"sessionId":null}
info: <-- POST /wd/hub/session 500 16.616 ms - 286 

error: Failed to start an Appium session, err was: Error: The following desired capabilities are required, but were not provided: deviceName

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}
info: <-- GET /wd/hub/status 200 1.698 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

Also if i select force device and provided a UDID after selecting the UDID I'm getting the issue "Failed to start an Appium session, err was: Error: Log capture did not start in a reasonable amount of time".
I have changed the stuimulator devices and i am facing the same issue.

Also please find the following go for your reference.

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --platform-version "8.1" --platform-name "iOS" --app "/Users/dhanasekarbabu/Downloads/untitled/UICatalog.app" --udid "F07654AE-E9B5-4A5F-956A-D20091413DAB" --show-ios-log --device-name "iPhone 5 (F07654AE-E9B5-4A5F-956A-D20091413DAB)"

info: Welcome to Appium v1.3.6 (REV 004f52f249d3513809e7d0734d9205d1fec19f8e)

info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"app":"/Users/dhanasekarbabu/Downloads/untitled/UICatalog.app","udid":"F07654AE-E9B5-4A5F-956A-D20091413DAB","deviceName":"iPhone 5 (F07654AE-E9B5-4A5F-956A-D20091413DAB)","platformName":"iOS","platformVersion":"8.1","showIOSLog":true,"defaultCommandTimeout":7200}

info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: <-- GET /wd/hub/status 200 12.528 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}
info: <-- GET /wd/hub/status 200 4.022 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}
info: --> GET /wd/hub/sessions {}
info: [debug] Responding to client with success: {"status":0,"value":[]}
info: <-- GET /wd/hub/sessions 200 1.527 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 5 (F07654AE-E9B5-4A5F-956A-D20091413DAB)"}}

info: Client User-Agent string: Appium (unknown version) CFNetwork/720.2.4 Darwin/14.1.0 (x86_64)

info: [debug] Using local app from command line: /Users/dhanasekarbabu/Downloads/untitled/UICatalog.app

info: [debug] Creating new appium session 8a4d5f38-d574-4338-85e3-443e04a26ed8
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.2

info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate

info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)

info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/dhanasekarbabu/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/dhanasekarbabu/Library/Application Support/appium/bootstrap/bootstrap-2911698fabce8e2c.js

info: [debug] Reusing dynamic bootstrap: /Users/dhanasekarbabu/Library/Application Support/appium/bootstrap/bootstrap-2911698fabce8e2c.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPhone 5 (F07654AE-E9B5-4A5F-956A-D20091413DAB)","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5 (F07654AE-E9B5-4A5F-956A-D20091413DAB) (8.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons

info: [debug] On a real device; cannot clean device state

info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"},"isShuttingDown":false},"sessionId":"8a4d5f38-d574-4338-85e3-443e04a26ed8"}
info: <-- GET /wd/hub/status 200 2.968 ms - 178 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"},"isShuttingDown":false},"sessionId":"8a4d5f38-d574-4338-85e3-443e04a26ed8"}

info: [debug] Cleaning up appium session

info: [debug] Error: Log capture did not start in a reasonable amount of time
    at null._onTimeout (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-log.js:137:10)
    at Timer.listOnTimeout (timers.js:110:15)

error: Log capture did not start in a reasonable amount of time

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Log capture did not start in a reasonable amount of time)","origValue":"Log capture did not start in a reasonable amount of time"},"sessionId":null}
info: <-- POST /wd/hub/session 500 10325.771 ms - 234 
info: [debug] Not pre-launching simulator
info: [debug] Creating iDevice object with udid F07654AE-E9B5-4A5F-956A-D20091413DAB
info: [debug] Checking app install status using: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id F07654AE-E9B5-4A5F-956A-D20091413DAB --bundle com.example.apple-samplecode.UICatalog

error: Failed to start an Appium session, err was: Error: Log capture did not start in a reasonable amount of time

Please help me to solve this issue.
Thanks in Advance

Regards,
Rajesh D

**Comment by ifeins** [comment]
I'm getting the same issue: "The following desired capabilities are required, but were not provided: deviceName".

I'm using the Appium.app version 1.3.7 on OSX (Yosemite).
I'm trying to run the `appium-sample-code/sample-code/examples/ruby/cucumber_android`

**Comment by penguinho** [comment]
You need to supply a device name in the capabilities. @bootstraponline That script probably needs to be updated to have a device name in the capabilities.

**Comment by edgy360** [comment]
Please reopen if providing the deviceName doesn't fix the issue.

**Comment by nitint007** [comment]
I have provided deviceName in json as well as updated same in the script, though I am getting the same error.
Can anyone help in please?
using Appium 1.4
Grid: 2.46
java version "1.8.0_45"
Win 8.1

**Comment by justin808** [comment]
@edgy360 I'm also trying the example `appium-sample-code/sample-code/examples/ruby/cucumber_android` and just downloaded everything. 

Where do you set the deviceName? Which file?

I also get the error:
```
error: Failed to start an Appium session, err was: Error: The following desired capabilities are required, but were not provided: deviceName
info: [debug] Error: The following desired capabilities are required, but were not provided: deviceName
    at [object Object].Capabilities.checkValidity (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/lib/server/capabilities.js:145:13)
    at [object Object].Appium.configure (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/lib/appium.js:238:35)
    at [object Object].<anonymous> (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/lib/appium.js:118:10)
    at [object Object].Appium.start (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/lib/appium.js:129:5)
    at exports.createSession (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/lib/server/controller.js:188:16)
    at Layer.handle [as handle_request] (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at /Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/lib/server/controller.js:39:7
    at Layer.handle [as handle_request] (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/Users/justin/.nvm/versions/node/v0.12.7/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: The following desired capabilities are required, but were not provided: deviceName)","origValue":"The following desired capabilities are required, but were not provided: deviceName"},"sessionId":null}
info: <-- POST /wd/hub/session 500 3.627 ms - 286
  The following desired capabilities are required, but were not provided: deviceName (Selenium::WebDriver::Error::WebDriverError)
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:657:in `raw_execute'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:122:in `create_session'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:52:in `new'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:52:in `for'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver.rb:86:in `for'
  /Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/appium_lib-6.0.0/lib/appium_lib/driver.rb:474:in `start_driver'
  /Users/justin/clients/paynearme/appium/sample-code/sample-code/examples/ruby/cucumber_android/features/support/env.rb:25:in `Before'
    Given I click about phone            # features/step_definitions/steps.rb:24
    Then the Android version is a number # features/step_definitions/steps.rb:28
```

**Comment by edgy360** [comment]
You need to specify it in the desired capabilities. I’m not familiar with the sample code for Ruby, but it should be towards the start of the session when this is defined.

The error is because of this being missing from your desired capabilities, rather than a GUI client error.

**Comment by nalabandian** [comment]
Im also getting the same error as below. 
Im using real device where the application is launching but im unable to get it in appium instector.
I am using selenium webdriver with java where I have set the desired capabilities as follows:
DesiredCapabilities capabilities = new DesiredCapabilities();
				capabilities.setCapability("browserName", CONFIG.getProperty("BROWSER_NAME"));
				capabilities.setCapability("version", "4.2.2");
				capabilities.setCapability("deviceName", "4100ea19ea");
				capabilities.setCapability("platformName", "Android");
				capabilities.setCapability("appPackage", "com.bt.bms");
				capabilities.setCapability("appActivity","com.bt.bms.activities.SplashActivity");
				driver = new RemoteWebDriver(new URL(
						"http://127.0.0.1:4723/wd/hub"), capabilities);


ERROR LOG:
------------------
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: The following desired capabilities are required, but were not provided: platformName, deviceName)","origValue":"The following desired capabilities are required, but were not provided: platformName, deviceName"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 3.157 ms - 314 
> info: --> POST /wd/hub/session {"desiredCapabilities":{}}
> info: Client User-Agent string: undefined
> info: [debug] Got configuration error, not starting session
> info: [debug] Cleaning up appium session
> info: [debug] Error: The following desired capabilities are required, but were not provided: platformName, deviceName
>     at [object Object].Capabilities.checkValidity (C:\Program Files\Appium\node_modules\appium\lib\server\capabilities.js:145:13)
>     at [object Object].Appium.configure (C:\Program Files\Appium\node_modules\appium\lib\appium.js:238:35)
>     at [object Object].<anonymous> (C:\Program Files\Appium\node_modules\appium\lib\appium.js:118:10)
>     at [object Object].Appium.start (C:\Program Files\Appium\node_modules\appium\lib\appium.js:129:5)
>     at exports.createSession (C:\Program Files\Appium\node_modules\appium\lib\server\controller.js:188:16)
>     at Layer.handle [as handle_request] (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:110:13)
>     at Route.dispatch (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:91:3)
>     at Layer.handle [as handle_request] (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\index.js:267:22
>     at Function.proto.process_params (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:100:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
>     at next (C:\Program Files\Appium\node_modules\appium\node_modules\express\lib\router\route.js:104:14)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: The following desired capabilities are required, but were not provided: platformName, deviceName)","origValue":"The following desired capabilities are required, but were not provided: platformName, deviceName"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 3.036 ms - 314 
> error: Failed to start an Appium session, err was: Error: The following desired capabilities are required, but were not provided: platformName, deviceName
> info: --> POST /wd/hub/session/cf241ba4-ecff-4ff6-a322-cef400440365/element {"using":"xpath","value":"//*[@id='savingsTotalCard']/div[2]/div[1]/div"}
> info: <-- POST /wd/hub/session/cf241ba4-ecff-4ff6-a322-cef400440365/element 404 1.196 ms - 40

**Comment by hillchan31** [comment]
parameters launched the appium and parameters used in the code should be same

1，start the appium with the parameters，
//  --platform-version "8.4"
//  --platform-name "iOS"
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "8.4" --platform-name "iOS" --app "/Users/Hill/Library/Developer/Xcode/DerivedData/BullsEye-hdhgcprnmenkwmdtwunchpljehin/Build/Products/Release-iphonesimulator" --show-ios-log --device-name "iPhone 6"

2，in Java，should use the parameters same to the parameters launched the appium
capabilities.setCapability("deviceName", "iPhone 6");
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("version", "8.4");

**Comment by KalveeduVijay** [comment]
You can make this job easier by setting up "preLaunchApplication" as 'True'
 in Appium GUI.

**Comment by sakshipujari** [comment]
I am using Appium v1.4 and trying to run the below code. I am getting the error message on eclipse console and on Appium server
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: The following desired capabilities are required, but were not provided: deviceName) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5.82 seconds
Build info: version: 'unknown', revision: '2aa21c1', time: '2016-08-02 14:59:43 -0700'

`	public static void main(String args[]) throws MalformedURLException
	{
	
		File appDir =new File("src");
		File app =new File(appDir, "<name of the apk file kept under src path>");

		DesiredCapabilities cap=new DesiredCapabilities();
		cap.setCapability("automationName", "Appium");
		cap.setCapability("platformname","Android");
		cap.setCapability("devicename", "Android");
       cap.setCapability("platformVersion", "23");        
			//	cap.setCapability("browserName", "Browser");
		cap.setCapability("app", app.getAbsolutePath());
				AndroidDriver driver=new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),cap);
		
	}`
