### ISSUE TITLE
Platform Version 8.2 is not available for iOS

### ISSUE THREAD

**Issue by chandrakanth1984** [appium/appium-dot-app#473]
We are using appium dot app for inspector and for other purposes. But we are not able to find 8.2 as iOS platform version in iOS settings. Could you please add this entry to the drop-down or else please let me know how I can start inspector using command prompt because I am able to start appium server with iOS version 8.2 using command prompt not from appium-dot-app

**Comment by edgy360** [comment]
Please could you confirm which version of Xcode and Appium you have?

**Comment by penguinho** [comment]
@chandrakanth1984, You can type in the textfield and enter 8.2

@edgy360, this is because our list has the versions hard-coded, we should probably be smart and also read them from the machine.

**Comment by chandrakanth1984** [comment]
Hi Jamie,

Solution provided by Dan Cuellar worked for me. Please find the xcode and
appium versions below,

XCode:Version 6.2 (6C131e)
Appium: I downloaded the latest version from
https://github.com/appium/appium-dot-app

Thanks,
Chandrakanth

On 24 March 2015 at 20:32, Jamie Edge <notifications@github.com> wrote:

> Please could you confirm which version of Xcode and Appium you have?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium-dot-app/issues/473#issuecomment-85422164>
> .
>



-- 
Thanks,
Chandrakanth Achyuta

**Comment by penguinho** [comment]
Fixed with https://github.com/appium/appium-dot-app/commit/4d4bea4178cdebeb9cdac19b0e83cbc6bbefd676
