### ISSUE TITLE
Appium GUI considers 1.3.6 as latest.

### ISSUE THREAD

**Issue by krish-300** [appium/appium-dot-app#475]
![image](https://cloud.githubusercontent.com/assets/6422306/6847456/ec5fc54c-d3ec-11e4-8941-307c114a790b.png)

**Comment by Astro03** [comment]
The logic here was a straight string compare and not a compare of actual ordinal number.  

It's easy to change.  Thx

Ciao,
Astro

**Comment by penguinho** [comment]
Try now. It's probably a caching issue. I don't see it.

Thanks for the early adoption
