### ISSUE TITLE
Application was unable to start application correctly (0xc000007b).Click Ok to close application

### ISSUE THREAD

**Issue by spkr22** [appium/appium-dot-app#478]
I get this error every time I click on Appium.exe. I am not sure if it is a issue with 32bit OS.
Please help on this.
"Application was unable to start application correctly (0xc000007b)"

**Comment by spkr22** [comment]
This one is resolved on installing .net framework in my machine.

**Comment by edgy360** [comment]
This is the repository for Appium.app (OS X). Please raise any further issues in the Appium.exe repository: https://github.com/appium/appium-dot-exe/issues
