### ISSUE TITLE
app to appium connection getting rejected 

### ISSUE THREAD

**Issue by TuckerSherman** [appium/appium-dot-app#479]
Running into a new problem when I attempt to launch the appium inspector from the new 1.3.7 -

 "Could not get list of sessions from Appium Server

Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object." 

I have provided all the required parameters, the server is running, and I can kickoff my ruby/cucumber test suite just fine.  When I dig into the code in the app it appears that when you hit the open inspector button the first thing it does is make a GET request to http://0.0.0.0:4723/wd/hub/status (or whatever the address and port that you've configured it with is)  

if I try this request from terminal ```$:curl http://0.0.0.0:4723/wd/hub/status``` i get a response just fine but when I track the request through in the code in SEUtility.m

``` +(NSDictionary*) performGetRequestToUrl:(NSString*)urlString error:(NSError**)error
{ ```	
``` NSURL *url = [NSURL URLWithString:[urlString stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];
NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url cachePolicy:NSURLRequestReloadIgnoringLocalCacheData timeoutInterval:DEFAULT_TIMEOUT];
    NSURLResponse *response;
    NSData *urlData = [NSURLConnection sendSynchronousRequest:request
											returningResponse:&response
														error:error]; ``` 

urlData is coming back nil... If I breakpoint lower in the method *error is empty, urlData is nil, but the response reads : 

```<NSHTTPURLResponse: 0x610000220480> { URL: http://0.0.0.0:4723/wd/hub/status } { status code: 403, headers {
    Connection = close;
    Via = "HTTP/1.1 proxy10417";
} }```
I am no NSURLConnection expert but why would I be I getting 403s (rejections) only from this connection?

**Comment by edgy360** [comment]
Could you try running using 127.0.0.1 (or whatever other address your network adapter has, if it needs to be accessible from other machines) rather than 0.0.0.0?

Something interesting I noticed in the response is `Via = "HTTP/1.1 proxy10417`. Are you using a proxy or VPN?

**Comment by edgy360** [comment]
Closing this issue. Please update the issue if you are still facing the same problem.
