### ISSUE TITLE
Platform version passed as null

### ISSUE THREAD

**Issue by moizjv** [appium/appium-dot-app#483]
- For more details please look at https://github.com/appium/appium/issues/4202

**Comment by edgy360** [comment]
I think that this has been fixed by a refactor a while ago.

Below is the command output I am getting on the development build.

```
lib/server/main.js --command-timeout "7200" --pre-launch --platform-version "7.1" --platform-name "iOS" --app "/Users/jamie/Development/Sample Projects/TestApp.app" --show-ios-log --device-name "iPhone 6"
```

@khyatid, as you originally reported this issue, please update this issue if you are still facing the same problem. Thanks.
