### ISSUE TITLE
[Android] Inspector's configuration looks at only bash

### ISSUE THREAD

**Issue by mttrs** [appium/appium-dot-app#484]
**What**: [Android] Inspector starts only with bash configuration.
**When**: Fire the inspector without setting in bash. Then see "Could Not Launch Appium Inspector".

```
Could not start a new session

Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object.
```

**Why**: The inspector see only bash. 

For non bash user like zsh and tcsh, they have to set the PATH in bash.

Proposal: 
1. See shell setting, decide which shell the user uses and confirm the PATH e.g. ANDROID_HOME.
2. Provide shell configuration GUI.
1. See shell setting from /etc/shells

``` bash
% cat /etc/shells
/usr/local/bin/zsh
/bin/bash
/bin/csh
/bin/sh
/bin/tcsh
/bin/zsh
```
- Previous discussion in the other appium repository
  https://github.com/appium/appium/issues/4947#issuecomment-95513183

**Comment by edgy360** [comment]
Thanks for taking the time to report this issue to us @mttrs.

Please could you let us know what you think would work best? Do you think that we should have an a text field to choose which shell we execute Appium using? Right now, we launch using `/bin/bash`.

**Comment by mttrs** [comment]
I prefer the 1st proposal that is to configure user shell. Appium might have to check the user shell, but it's not so difficult, I think. Just checking `$SHELL` or `$0` looks enough. What do you think?

- Merit:  
-- No GUI implementation.  
-- User doesn't have to think about their shell.
