### ISSUE TITLE
Unable to find "Record" button on Inspector window

### ISSUE THREAD

**Issue by dhiraj-infosys** [appium/appium-dot-app#491]
**Environment:**
- Version:1.4.0.0
- OS: Windows 7
- IDE: Eclipse
- Application: Android

**Steps:**
- Connect an android application with appium
- Click Launch to start the server.
- Now Open Inspector window.

**Observed:**
- I can take the screen shot and can locate the UI element. **But I cannot record the Script. How do I record the script?**

**Expected:**
- Recorder option is available.

**Comment by penguinho** [comment]
This needs to be logged against https://github.com/appium/appium-dot-exe
