### ISSUE TITLE
Unable to load node configuration file to register with grid and appium background is white

### ISSUE THREAD

**Issue by JamalMSaad** [appium/appium-dot-app#496]
Hi,
I have appium 1.4.0 version , and when i start appium and launch it , I am getting "error: Unable to load node configuration file to register with grid" issue , also the background of the appium screen is now in white , how can i revert it back to black (please see the attached screen shot)

Thx
Jamal
![screen shot 2015-06-11 at 9 51 56 am](https://cloud.githubusercontent.com/assets/12841220/8109885/eabd1972-1061-11e5-8e67-2a417ef3c8be.png)

**Comment by penguinho** [comment]
Have you checked that the "Selenium Grid Config" checkbox is not checked in the general settings section.

Also what OS are you on?

**Comment by JamalMSaad** [comment]
Thx Penguinho for you reply,"Selenium Grid Config" was checked i unchecked it and i am no longer having the error issue, do you have any idea how to change the background color to black.
Thx in advance.

**Comment by edgy360** [comment]
Closing as the original issue was resolved. Please raise another issue if you are still facing the issue with the background in the latest release.
