### ISSUE TITLE
Appium screen background color is white 

### ISSUE THREAD

**Issue by JamalMSaad** [appium/appium-dot-app#497]
Hi, I have appium 1.4.0 version, can anyone help me to change the background color of Appium screen from white to balck .
Thx in Advance.

![appium background](https://cloud.githubusercontent.com/assets/12841220/8158119/e0deca96-1362-11e5-9f02-b90eddbc72c2.png)

**Comment by edgy360** [comment]
Please could you try reinstalling Appium? It shouldn't be that colour, and as such there isn't an option to change it.

It looks like the background image is missing from the app somehow.

**Comment by JamalMSaad** [comment]
Thx for your reply, actually i reinstalled it several times and still have
the pb, i use mini mac,  can you please send me the missing file in case
you know which is.
Thx in advance

**Comment by edgy360** [comment]
Unfortunately I can't just send the single file, as it's part of the bundle.

Are you using any sort of antivirus that could be blocking Appium components from loading?

**Comment by JamalMSaad** [comment]
I am using symantec anti-virus, but i wasn't have this issue before

**Comment by edgy360** [comment]
Something must be blocking the image loading somehow. Please try disabling the antivirus program temporarily and then see if the issue persists.

**Comment by JamalMSaad** [comment]
Ok, i will try, thx

**Comment by JamalMSaad** [comment]
Sorry, i am using a mac and it doesn't have an antivirus, i there anything
else that could block the image from loading

**Comment by edgy360** [comment]
Please reopen if you are still facing this issue in the latest release.

**Comment by Pritesh-Jawale** [comment]
facing same issue.... reinstalled multiple times with different versions.
