### ISSUE TITLE
[Android] Android emulators showing blank page, not loading

### ISSUE THREAD

**Issue by ynotdraw** [appium/appium-dot-app#498]
Hello, I'm running into an issue with the Android Appium emulators. I was told to submit this issue to this forum after posting here https://github.com/appium/appium/issues/4963#issuecomment-112123406 and here https://discuss.appium.io/t/android-emulators-showing-blank-page-not-loading/4781/1

I've been using Sauce Labs to run tests against their Android emulators. I have moved away from the AndroidDriver Webview App and started using Appium. I use the emulator to launch a webpage and run automated UI tests against the Android device's browser. In my automated test, most of the pages are displayed and the tests pass; however, when it redirects to a URL after clicking a button on the UI, the screen just displays blank and it appears to be loading forever.

This happens for many tests which redirect to this URL, but ONLY for the Android emulators. I'm not sure what you need to troubleshoot, so please let me know and I'll add any info you may need. Please note that this only happens with the Android tests - all other test environments work flawlessly and do not have this issue on a redirect. I can provide a sauce labs URL if needed. Thanks!
![d81092b0-e742-11e4-873d-21072d6292c6](https://cloud.githubusercontent.com/assets/8069555/8208390/6543aca2-14d5-11e5-8e3b-462d228125a5.png)

**Comment by Jonahss** [comment]
This is an issue with the android emulator, not with the appium.app tool. see discussion: https://github.com/appium/appium/issues/4963
