### ISSUE TITLE
Error when trying to run Appium on Xcode 

### ISSUE THREAD

**Issue by dobybest** [appium/appium-dot-app#502]
-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G
 
-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G
 
|[0G/Users/Florin/Library/Developer/Xcode/DerivedData/Appium-comdoyaccmdjdygrqnwmvucjgdxg/Build/Products/Debug/Appium.app/Contents/Resources/node/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found

 
/Users/Florin/Library/Developer/Xcode/DerivedData/Appium-comdoyaccmdjdygrqnwmvucjgdxg/Build/Products/Debug/Appium.app/Contents/Resources/node/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found
[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35moptional dep failed, continuing[0m utf-8-validate@1.1.0
[0m[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35moptional dep failed, continuing[0m bufferutil@1.1.0
[0m/[0G-[0G\[0G|[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
[0m|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G-[0G\[0G|[0Gsh: node: command not found
-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G-[0G\[0G|[0G[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
[0m-[0G\[0G|[0G/[0G-[0G\[0G|[0G/[0G-[0G\[0G|[0G[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
[0m[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
[0m[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
[0m[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Darwin 14.3.0
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35margv[0m "/Users/Florin/Library/Developer/Xcode/DerivedData/Appium-comdoyaccmdjdygrqnwmvucjgdxg/Build/Products/Debug/Appium.app/Contents/Resources/node/bin/node" "/Users/Florin/Library/Developer/Xcode/DerivedData/Appium-comdoyaccmdjdygrqnwmvucjgdxg/Build/Products/Debug/Appium.app/Contents/Resources/node/bin/npm" "install" "appium@1.4.1"
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mnode[0m v0.12.4
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mnpm [0m v2.10.1
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mfile[0m sh
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mcode[0m ELIFECYCLE
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35merrno[0m ENOENT
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35msyscall[0m spawn
[0m
[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m appium-chromedriver@2.1.3 install: `node install-npm.js`
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m spawn ENOENT
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m 
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Failed at the appium-chromedriver@2.1.3 install script 'node install-npm.js'.
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m This is most likely a problem with the appium-chromedriver package,
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m not with npm itself.
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Tell the author that this fails on your system:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     node install-npm.js
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m You can get their info via:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     npm owner ls appium-chromedriver
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m There is likely additional logging output above.
[0m
[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Please include the following file with any support request:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     /Users/Florin/Library/Developer/Xcode/DerivedData/Appium-comdoyaccmdjdygrqnwmvucjgdxg/Build/Products/Debug/Appium.app/Contents/Resources/npm-debug.log
[0m

Xcode version : 6.4
OS X version : 10.10.4

If you need more info please let me know and i provide you .

Thanks for helping,
Florin

**Comment by edgy360** [comment]
Please go to Build > Clean and then try again.

Also, why are you needing to run via Xcode? Can you instead build out and then run as a standalone app if you need a modified version?

**Comment by dobybest** [comment]
Hi ,

I tried clean already but with no success .
I need to launch this from Github project because my client want to add some custom things on existing app .


Any help for this is much appreciated .
Thanks

**Comment by penguinho** [comment]
This has been broken for a few months. It's a problem with the appium server. It would be great if someone could fix the server so that you can run npm install from a local folder instead of from an installed path. In the meantime you need to copy the appium folder over to inside the .app to get it to continue. I'll try to come up with a workaround in the next few days. If you just want to use the .app you can change the version to something like 1.3.0 in Info.plist and it should try to download a version of appium that still installs properly

**Comment by dobybest** [comment]
Thanks for your answer ,
I hope you will find an workaround for this because i need the last version on appium working so i can apply my changes on this .
Thank you very much and i'm waiting for an answer from you fast as you can .

Have a nice day ,
Florin

**Comment by dobybest** [comment]
Hi @penguinho ,
Can you provide me some info to make the project running in Xcode until you manage to make an workaround on this version like a git revision to revert and/or an Xcode version .

Thanks,
Florin

**Comment by dobybest** [comment]
Hi @penguinho ,
Do you have any update on this issue ?

Thanks,
Florin

**Comment by penguinho** [comment]
copy the appium source into Appium.app/Contents/Resources/node_modules/ after building. It will work then

**Comment by penguinho** [comment]
Download the last published version of Appium.app and copy the Contents/Resources/node_modules folder into your version that Xcode built. It will work then

**Comment by michaelgallacher** [comment]
I can't run the Xcode-built appium.app either...the node and node_modules folders are empty. Why does the released/shipping build of Appium.app have these folders populated?  What's different about the build process?

**Comment by Astro03** [comment]
Appium.app is published with those folders populated to make it easier for the general masses. IF it was not populated, then each person who downloads the app, will then automatically download the node and node_modules necessary for appium to run.

**Comment by edgy360** [comment]
I've tested and this seems to be working ok now. Please reopen if you still cannot compile the app using the .xcworkspace file.
