### ISSUE TITLE
Please release .app for 1.4.11

### ISSUE THREAD

**Issue by moizjv** [appium/appium-dot-app#506]
We now have appium 1.4.11 that has ios9 support :)

**Comment by ianmdawson** [comment]
This would be quite helpful

**Comment by ashishraj14** [comment]
Hi folks,
am quite new to Appium and making my way around on how to install appium and run tests.
Currently , I have used the 1.4.8 dmg file to install appium on mac, where can i get the dmg file for 1.4.11 so i can install the latest appium.app on this mac.

Thanks,

**Comment by pavelzag** [comment]
Subscribing to the issue

**Comment by rompic** [comment]
+1

**Comment by ianmdawson** [comment]
If you'd like a temporary workaround, you should be able to update the appium server by updating the node_module within the Appium.app bundle located here: `Appium.app/Contents/Resources/node_modules`

**Comment by pavelzag** [comment]
Interesting, I'll check once I get home, thanks a lot!

**Comment by seleniumappiumnewbie** [comment]
Ian and All,
Can you explain in step by step details how to get the temporary workaround to get the new version 1.4.11 Appium.app? I'm a newbie with Selenium, Appium, and mac terminal. Do you know when they will update the appium.io site to have the new 1.4.11 Appium app version?
Thanks for your help.

**Comment by Astro03** [comment]
I believe if you delete the node modules folder a new download will occur for the latest.  ( but I'm not near a computer right now so I can't verify this. )

Ciao,
Astro
Sent from my phone

On Sep 20, 2015, at 14:16, seleniumappiumnewbie <notifications@github.com> wrote:

Ian and All,
Can you explain in step by step details how to get the temporary workaround to get the new version 1.4.11 Appium.app? I'm a newbie with Selenium, Appium, and mac terminal. Do you know when they will update the appium.io site to have the new 1.4.11 Appium app version?
Thanks for your help.

**Comment by pavelzag** [comment]
There was a nice post on Appium discussions that explain it well, I'll try to find it for you..

**Comment by pavelzag** [comment]
Check Sruthi's reply and see if you make it work
https://discuss.appium.io/t/new-xcode-breaks-ios-emulator-initiation/6051/6
