### ISSUE TITLE
Appium GUI Settings reset

### ISSUE THREAD

**Issue by radugr** [appium/appium-dot-app#508]
Hi,

I don't know exactly how this happened, but somehow, in the Appium GUI for OSX, Maximum Log Length got set to 0. This means I can't see any logs in the GUI. It doesn't let me change it (the field can't be edited). I tried uninstall/reinstall and it still keeps the same settings as last time it was installed! 
I searched for all .appiumconfig files and removed them, then uninstall/reinstall, and it STILL keeps the settings! Where does it get them from? How can I reset all the settings?
If I use appium server from terminal, logs appear fine there.
Any ideas?

Thanks,
-Radu

**Comment by Astro03** [comment]
Have you tried to reset your settings?

Open Appium
Go to Menu Bar (the one at the top of your screen) -> Appium -> Reset Preferences

ciao,
ASTRO

**Comment by radugr** [comment]
No idea how I missed this option. It reset the Maximum log length and now I can see the logs again. Still need to find out what caused this in the first place, but nice to have a quick fix for it.
Thank you very much!

-Radu

**Comment by Astro03** [comment]
open this issue again if you need.
