### ISSUE TITLE
Please release .app for 1.4.13

### ISSUE THREAD

**Issue by scottdixon** [appium/appium-dot-app#509]
Can you please release 1.4.13 along with https://github.com/appium/appium-dot-app/issues/506

1.4.13 now supports iOS9.1.

Thank you

**Comment by joshrlesch** [comment]
agree with this, would be nice to use this again!!!

**Comment by SConrad-Whoop** [comment]
This would be a great help, the new XCUI tests in Xcode7 are not working out as I had hoped so I'd like to get back with Appium!

**Comment by penguinho** [comment]
done

**Comment by curtissiemens** [comment]
Regarding new OS-X build:
The build looks like it works, but the versioning & upgrade parts have issues.
If you have 1.4.8 installed & check for updates it says you have the latest version.
If you download 1.4.13 and install it & then (for kicks) "check for updates" it says wants you to upgrade with a "newer" version:
Your version: 1.4.13 (Draco)
Latest version: 1.4.8 (Draco)

**Comment by Astro03** [comment]
@curtissiemens fixed.

**Comment by Astro03** [comment]
@curtissiemens  actually, i'm going to leave it how it was.  i think 1.4.13 might be broken, that's why latest is pegged at 1.4.8. See #510

**Comment by luonglne** [comment]
Thanks Astro03 for reference to #510 for a workaround but would someone rebuild 1.4.13 or post the new version please?
