### ISSUE TITLE
1.4.13 throws uncaughtException: Cannot find module 'appium-instruments'

### ISSUE THREAD

**Issue by chrigrahcisco** [appium/appium-dot-app#510]
Manually installed 1.4.13 from http://appium.io/  over 1.4.8   and upon first lauch received the following error.

Xcode 7.0.1
OS X 10.10.5

`2015-10-12 13:30:17:169 - error: uncaughtException: Cannot find module 'appium-instruments' date=Mon Oct 12 2015 09:30:17 GMT-0400 (EDT), pid=25418, uid=501, gid=20, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.7, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --command-timeout, 50000, --session-override, --debug-log-spacing, --log, /Users/chrigrah/Downloads/appium.log, --log-timestamp, --platform-version, 9.0, --platform-name, iOS, --app, /Users/chrigrah/Library/Developer/Xcode/DerivedData/<MY_AUT>.app, --show-ios-log, --device-name, iPhone 6, --launch-timeout, 120000], rss=76230656, heapTotal=61778432, heapUsed=26814384, loadavg=[1.80810546875, 2.1240234375, 2.00390625], uptime=1817917, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=336, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=278, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=14, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js, function=, line=4, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=19, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=, line=15, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false], stack=[Error: Cannot find module 'appium-instruments',     at Function.Module._resolveFilename (module.js:336:15),     at Function.Module._load (module.js:278:25),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js:4:14),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:15:19),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12)]`

**Comment by chrigrahcisco** [comment]
Proposed solution posted here: http://stackoverflow.com/questions/33080101/appium-failed-to-start-uncaught-error-instruments/33080553#33080553

**Comment by penguinho** [comment]
@chrigrahcisco Can you send me a copy of the working node_modules appium folder that you have and I'll re-release the mac app

**Comment by chrigrahcisco** [comment]
I wish I could, I haven't been able to figure out exactly what is missing to copy them over successfully.

**Comment by scastria** [comment]
The solution is to fix the bad symlinks contains within the dmg distribution.

Inside the Contents of appium.dmg are symlinks to node modules pointing to /usr/local/lib/node_modules instead of ../submodules:

lrwxr-xr-x 1 shawn admin 38 Oct 8 09:22 appium-adb -> /usr/local/lib/node_modules/appium-adb
lrwxr-xr-x 1 shawn admin 40 Oct 8 09:20 appium-atoms -> /usr/local/lib/node_modules/appium-atoms
drwxr-xr-x@ 17 shawn admin 578 Oct 8 09:09 appium-chromedriver
lrwxr-xr-x 1 shawn admin 46 Oct 8 09:20 appium-instruments -> /usr/local/lib/node_modules/appium-instruments
drwxr-xr-x@ 14 shawn admin 476 Jul 21 03:27 appium-support
lrwxr-xr-x 1 shawn admin 41 Oct 8 09:20 appium-uiauto -> /usr/local/lib/node_modules/appium-uiauto

**Comment by ShankarGarg** [comment]
Solution worked for me as well. Thanks!!

**Comment by findmeetu** [comment]
@penguinho Can you please re release the mac app? I would like to use a working released version. Thanks!

**Comment by moizjv** [comment]
`cd /Applications/Appium.app/Contents/Resources/node_modules/appium
npm install`

**Comment by scastria** [comment]
One of the reasons of using the mac app is to avoid having to install brew, npm, node, etc.  therefore suggesting to run an npm install to fix this issue for appium-dot-app does not make sense.

**Comment by findmeetu** [comment]
@moizjv I ran the above command and got past the error. However, instruments does not launch. I am trying this for the first time with the sample TestApp.app. 

Xcode version - 7.0.1

I am getting the following error:

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --address "127.0.0.1" --command-timeout "7200" --debug-log-spacing --platform-version "9.0" --platform-name "iOS" --app "/Users/vikram/appium-git/sample-code/sample-code/apps/TestApp/build/release-iphonesimulator/TestApp.app" --show-ios-log --device-name "iPhone 6" --native-instruments-libwarn: Instruments socket client never checked in; timing out (global)

<snip>

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Killall instruments

info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall Simulator
info: [IOS_SYSLOG_ROW ] Oct 19 09:11:08 vikrams-Mac-mini DTServiceHub[13840]: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn

info: Launching instruments

info: [debug] Attempting to run app on iPhone 6 (9.0) [
info: On xcode 7.0, instruments-without-delay does not work, skippinginstruments-without-delay
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.0) [" /Users/vikram/appium-git/sample-code/sample-code/apps/TestApp/build/release-iphonesimulator/TestApp.app -e UIASCRIPT "/Users/vikram/Library/Application Support/appium/bootstrap/bootstrap-1cde5890b4065569.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And launch timeouts (in ms): {"global":90000}

**Comment by scastria** [comment]
Are you referring to running the above "npm install" command?  if so, I am not sure what that will do to your appium-dot-app mac app.  i would think that might mix the mac app approach and the command line approach to using Appium.

For me, I have no brew, npm, node, etc on my machine.  I download the appium-dot-app.  I fix the symlinks inside the .app as described above.  I specify the --native-instruments-lib in the custom server flags and everything works fine, including the inspector.

**Comment by findmeetu** [comment]
@scastria Thanks for your reply. I tried the steps you described as well. The inspector came up one time. However, after restarting the appium app, I have been seeing the above error. Could not launch instruments - Could not create a new session. This might be an unrelated error but I am not sure.

**Comment by chrigrahcisco** [comment]
@scastria   care to share specific step-by-step directions on how you corrected this issue so the rest of us can get up and running?

**Comment by scastria** [comment]
I did up above when I said "The solution is to fix the bad symlinks contained within the dmg distribution."

so open up a terminal and fix the links with the ln command.

**Comment by JuanMaCuevas** [comment]
exactly, that fixed it for me. Here is how to do it:
https://github.com/appium/appium-dot-app/issues/512#issuecomment-149594517

**Comment by samiramin** [comment]
@scastria Can you pls provide commands? The above commands is not working.

**Comment by edgy360** [comment]
Should be fixed in the current version of Appium. Please reopen if not.

**Comment by nirortal** [comment]
It's helped.
Thank you!!!!
