### ISSUE TITLE
appium.dmg 1.4.13 thinks it is older than 1.4.8

### ISSUE THREAD

**Issue by scastria** [appium/appium-dot-app#511]
It looks like the appium.dmg version check is doing a simple alpha sort so it thinks 1.4.8 is more recent than 1.4.13.

**Comment by seleniumappiumnewbie** [comment]
I see the same issue. I have 1.4.13 installed, but it thinks it is older than 1.4.8. 
After deleting Appium dmg GUI app 1.4.8 and installing Appium 1.14.13 dmg GUI app, I keep seeing this alert message pop up when I open the Appium server. The alert says Would you like to download the latest version of Appium.app and restart? 
Your Version: 1.4.13(Draco) 
Latest Version: 1.4.8(Draco)

How do I disable this message alert from popping up again?
Thanks.

![screen shot 2015-10-15 at 8 17 22 pm](https://cloud.githubusercontent.com/assets/14364579/10533084/cfe14c92-7379-11e5-8598-46c0bf8c6040.png)

**Comment by toejough** [comment]
Reverse problem with 1.4.8 - checking for updates returns a message that says I've got the most recent version, even though 1.4.13 is available.

**Comment by igalep** [comment]
Have the same issue  as well

**Comment by furmanjmx** [comment]
just turn off check for updates in settings))

**Comment by edgy360** [comment]
Closing this issue as there are a few releases since then.

Related to a fix in the future, this is just because the update.json file that we check was not updated. It works just by directly comparing versions, rather than comparing if one number is larger than the other.
