### ISSUE TITLE
Appium 1.4.13 missing iOS 9 / iPhone 6s 6Plus s 

### ISSUE THREAD

**Issue by igalep** [appium/appium-dot-app#514]
I'm trying to set iOS 9 with iPhone 6 / 6Plus s devices but the Appium app for mac is missing them in the Devices / Platform versions

**Comment by igalep** [comment]
a workaround is to write the values manually - but still need to be fixed

**Comment by scottdixon** [comment]
Appium 1.4.13 doesn't support iPhone 6s or iPhone 6s Plus. You can get it working by adding them to https://github.com/appium/appium/blob/master/lib/devices/ios/ios.js#L1027-L1045

If you make the change please submit a PR to Appium to have them in the next release.

**Comment by SrinivasanTarget** [comment]
@scottdixon Hope this will resolve.Please review the same.
