### ISSUE TITLE
Appium always picks up 1st device in the adb list.

### ISSUE THREAD

**Issue by gerelasumit** [appium/appium-dot-app#519]
Hi, I have bunch of appium nodes connected to the selenium grid. I used selenium grid as hub in for testing. Below are the logs

ADB Logs: 
$ adb devices
List of devices attached
emulator-5554	device
emulator-5556	device

1st appium node which is started using this command:
appium --session-override --nodeconfig ~/Desktop/android-testing/node-configs/android5.0.json -p 4730
info: Client User-Agent string: Apache-HttpClient/4.3.1 (java 1.5)
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : version
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] No appPackage desired capability or server param. Parsing from apk.
info: [debug] https://storage.googleapis.com/xperiel-public/Sandbox.apk downloaded to /var/folders/99/k0168shn56dg31wq30940pbc0000gp/T/1151013-37093-gzqk6b/appium-app.apk
info: [debug] Creating new appium session 871478db-9371-465b-b91f-8bded3af503a
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.8.0_45
info: [debug] Checking whether adb is present
info: [debug] Using adb from /usr/local/share/android-sdk/platform-tools/adb
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /usr/local/share/android-sdk/build-tools/22.0.1/aapt
info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: /usr/local/share/android-sdk/build-tools/22.0.1/aapt dump badging /var/folders/99/k0168shn56dg31wq30940pbc0000gp/T/1151013-37093-gzqk6b/appium-app.apk
info: [debug] badging package: com.xperiel.android.sandbox
info: [debug] badging act: com.xperiel.android.sandbox.login.LogInActivity
info: [debug] Parsed package and activity are: com.xperiel.android.sandbox/com.xperiel.android.sandbox.login.LogInActivity
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /usr/local/share/android-sdk/platform-tools/adb devices
info: [debug] 2 device(s) connected
info: Found device emulator-5554
info: [debug] Setting device id to emulator-5554
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 wait-for-device
info: [debug] executing cmd: /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}},"sessionId":"871478db-9371-465b-b91f-8bded3af503a"}
info: <-- GET /wd/hub/status 200 1.342 ms - 156 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}},"sessionId":"871478db-9371-465b-b91f-8bded3af503a"}
info: [debug] Getting device API level
info: [debug] executing cmd: /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: Device API level is: 19
info: [debug] Extracting strings for language: default
......

android5.0.json file contents:
{
  "capabilities":[
  {
    "browserName": "android",
    "version": "5.0",
    "maxInstances": 1,
    "platform": "ANDROID",
    "deviceName": "emulator-5556"
  }
],
  "configuration":
  {
    "cleanUpCycle": 2000,
    "timeout": 30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url": "http://some ip:4731/wd/hub",
    "host": "some ip",
    "port": 4731,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "some ip"
  }
}

I have similar configuration for 2nd appium node but it just uses emulator-5554 with android 4.4

Driver capabilities are as follows: 
 DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability("deviceName","emulator-5556");
    capabilities.setCapability("version", "5.0");
    capabilities.setCapability("app", appPath);
    return capabilities;

It picks up the right selenium node with version 5.0 of android but always uses the 1st device from the adb device list (evident from the logs), is there something wrong on my side? or appium is not able to work well with selenium grid?

Thanks!

**Comment by kcinman11358** [comment]
I had the same problem. If I remember correctly, I set the udid (yes, even for android) to whatever it was in the adb device list

            //Bluestacks
            //deviceName = "Bluestacks";
            //udid = "emulator-5554";

            //GenyMotion
            deviceName = "GenyMotion";
            udid = "192.168.56.101:5555";

            //Real Device
            //deviceName = "GalaxyS5";
            //udid = "5e359129";


capabilities.SetCapability("udid", udid);

**Comment by gerelasumit** [comment]
I did the same too. I set the appium nodes when starting the appium nodes. That worked and picks up the right device always.

**Comment by vishal-jalgaonkar** [comment]
Please add "udid" in the capabilities,
e.g
capabilities.setCapability("udid", deviceName)

or else ADB selects the first device it finds.

**Comment by kcinman11358** [comment]
@vishal-jalgaonkar , you don't set the deviceName as the udid, you should set it's ip address as the udid

example:
capabilities.SetCapability("udid", udid);

**Comment by andrepm06** [comment]
@kcinman11358 Should i do it for physical devices? And should i remove deviceName of json files?

**Comment by andrepm06** [comment]
Can i have som help on it?

I have two physical devices connected, and i want to run my tests on both.

Here's my json files:

{
  "capabilities":
    [
      {
        "browserName":"Lolipoop",
        "version":"5.1",
        "platform":"ANDROID",
        "maxInstances": 1
      }
    ],
  "configuration":
  {
    "cleanUpCycle":2000,
    "timeout":10800,
    "url":"http://127.0.0.1:4733/wd/hub",
    "host": "127.0.0.1",
    "port": 4733,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "127.0.0.1"
  }
}

and 

{
  "capabilities":
    [
      {
        "browserName":"Lolipoop",
        "version":"5.1",
        "platform":"ANDROID",
        "maxInstances": 1
      }
    ],
  "configuration":
  {
    "cleanUpCycle":2000,
    "timeout":10800,
    "url":"http://127.0.0.1:4723/wd/hub",
    "host": "127.0.0.1",
    "port": 4723,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "127.0.0.1"
  }
}

I started hub:

`java -jar selenium-server-standalone-2.52.0.jar -port 4444 -role hub`

Started node:
`node.exe node_modules\appium\bin\appium.js -a 127.0.0.1 -p 4723 -bp 4726 - U 0429058934 --nodeconfig C:\Users\andre.mendes\Desktop\workspace\powerpro\json\motoG.json´

´node.exe node_modules\appium\bin\appium.js -a 127.0.0.1 -p 4733 -bp 4736 - U LGH815f0d0b288 --nodeconfig C:\Users\andre.mendes\Desktop\workspace\powerpro\json\motoG.json´

And this is my capabilities:


`def setUp(self):		
		
		desired_caps = {}
		desired_caps['platformName'] = 'Android'
		desired_caps['platformVersion'] = '5.1'
		desired_caps['deviceName'] = ''
		desired_caps['app'] = os.path.abspath(os.path.join(os.path.dirname(__file__), 'C:/Users/andre.mendes/Desktop/workspace/powerpro/apps/powerpro.apk'))
		desired_caps['appPackage'] = 'com.psafe.powerpro'
		desired_caps['appActivity'] = '.MainActivity'
		desired_caps['noReset'] = False
		self.driver = webdriver.Remote('http://127.0.0.1:4444/wd/hub', desired_caps)
		self.driver.implicitly_wait(15)`

But unfortunately, my test only run in one device : (

**Comment by kcinman11358** [comment]
i don't see a udid in there

**Comment by andrepm06** [comment]
@kcinman11358 
Do i have to use udid instead deviceName?

`desired_caps['udid'] = '0429058934'` ?

I am trying to run my test in two devices. Why i have to put an udid of one of those?

**Comment by kcinman11358** [comment]
put the udid for the device you want to use

**Comment by andrepm06** [comment]
Well, i already tried and it didnt worked : (

`def setUp(self):		
		
		desired_caps = {}
		desired_caps['platformName'] = 'Android'
		desired_caps['platformVersion'] = '5.1'
		desired_caps['deviceName'] = '0429058934'
                desired_caps['udid'] = '0429058934'
		desired_caps['app'] = os.path.abspath(os.path.join(os.path.dirname(__file__), 'C:/Users/andre.mendes/Desktop/workspace/powerpro/apps/powerpro.apk'))
		desired_caps['appPackage'] = 'com.psafe.powerpro'
		desired_caps['appActivity'] = '.MainActivity'
		desired_caps['noReset'] = False
		self.driver = webdriver.Remote('http://127.0.0.1:4444/wd/hub', desired_caps)
		self.driver.implicitly_wait(15)`

What if i want to run my script in two devices?

**Comment by kcinman11358** [comment]
yea, put a deviceName and a udid.

if you want to run on two devices, then you should have a switch in there

**Comment by gerelasumit** [comment]
You need to start the appium instance with -U flag.
Eg:
appium --port 4727 --command-timeout "7200" --session-override --nodeconfig "path/to/node/config/json" -U "device-udid".

**Comment by andrepm06** [comment]
@kcinman11358 I tried using an array/dictionary, but got nothing :/

`def setUp(self):		
		
		util = Util()			
		
			#self.driver = util.setAppium('5.1', 'Android', 'C:/Users/andre.mendes/Desktop/workspace/powerpro/apps/powerpro.apk',
		                                   #'com.psafe.powerpro', '.MainActivity')
		desired_caps = {}
		desired_caps['platformName'] = 'Android'
		desired_caps['platformVersion'] = '5.1'
		desired_caps['deviceName'] = util.devices()
		desired_caps['udid'] = util.devices()
		desired_caps['app'] = os.path.abspath(os.path.join(os.path.dirname(__file__), 'C:/Users/andre.mendes/Desktop/workspace/powerpro/apps/powerpro.apk'))
		desired_caps['appPackage'] = 'com.psafe.powerpro'
		desired_caps['appActivity'] = '.MainActivity'
		desired_caps['noReset'] = False
		self.driver = webdriver.Remote('http://127.0.0.1:4444/wd/hub', desired_caps)
		self.driver.implicitly_wait(15)`	

`def devices(self):
		return {
			'a': '0429058934',
			'b': 'LGH815f0d0b288',
		}
	`

@gerelasumit i did that already

**Comment by edgy360** [comment]
I'm closing this on the Appium.app issue tracker as this is related to the main Appium server. If you are still facing this issue then please post on [Appium Discuss](https://discuss.appium.io) or if you feel this is a bug, on the [main Appium issue tracker](https://github.com/appium/appium/issues). Thanks!

**Comment by idhoum** [comment]
Hi,

can one of you give us a real working exemple

**Comment by santosh47billion** [comment]
@JamieEdge -Can you explain me hoe to run our appium code in Mobile azure and how to provide url of cloud currently when i am running my same code with my device its working find but when we try to run same code on azure its error shows.

**Comment by JamieEdge** [comment]
This is no longer maintained. Please use Appiun Discuss.
