### ISSUE TITLE
Please release 1.4.16

### ISSUE THREAD

**Issue by moizjv** [appium/appium-dot-app#520]
We have released a new version of appium server; please make it available through dot-app :)

**Comment by rompic** [comment]
+1

**Comment by NikolayStanoev** [comment]
+1

**Comment by Logrologist** [comment]
+5 (everyone in our QA department in one upvote)

Why is there not a dmg for anything passed 1.4.13?

**Comment by vikramvi** [comment]
@Logrologist @NikolayStanoev @rompic  @moizjv 
 can you please try as per details in https://github.com/appium/appium-dot-app/issues/531

I didn't work for me yet , trying to find answer
