### ISSUE TITLE
Appium 1.4.13 inspector doesn't recognize UITableCellsViews inside UITableview

### ISSUE THREAD

**Issue by crisnieto** [appium/appium-dot-app#521]
Hi,
The issue i'm finding is that Appium's inspector doesn't recognize the cells inside my UITable.

The UITable in the app contains an UIView and UICells. Strangely, Appium only recognizes the UIView  recognized as UIAElement, tbut not the Cells (they are in the same hierarchy level)
I made sure in the code that the table and the cells have configured their Identifiers Id, are accessible and also made sure that they don't contain hidden elements.

Here is the XML part of the Appium's Inspector where it only gets the Table with the UIView inside, ignoring the cells.

    <UIATableView name="Country Table" label="Country Table" value="rows 1 to 14 of 15" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1" x="0" y="64" width="375" height="603">
                <UIAElement name="View" label="View" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/1/0" x="0" y="64" width="375" height="10">
                </UIAElement>
            </UIATableView>

The variable "value" inside the UIATable XML says "rows 1 to 14 of 15" buy then when I get to inspect inside the table there is only de UIView

I also attach the image of the inspector.

![uitable_issue](https://cloud.githubusercontent.com/assets/15731030/11300034/75a5e924-8f6a-11e5-98b3-05e2e0b285bd.png)

Specs:
Appium 1.4.13
Mac OSX Yosemite 10.10.5
iPhone Simulator 9.1, also present on real devices.

Thanks.

**Comment by mbelyaeva91** [comment]
Hi!
I'm experiencing the same issue where UI elements inside UICollectionViewCells are not recognized.
I'm running 
Appium 1.4.13
OS X El Capitan 10.11.1 and real devices

**Comment by crisnieto** [comment]
I found that this is random, running on the same conditions, sometimes the inspector gets to inspect the cells inside, but it's not always, most of the times, the inspector doesn't get it. Also when it did get the cells, i record an automated test to tap the cell, but when running the test, appium doesn't seems to found any cell.

![captura de pantalla 2015-11-25 a las 14 30 29](https://cloud.githubusercontent.com/assets/15731030/11404650/d3e56d82-9381-11e5-88a2-5e7200054565.png)

Any thoughts?

**Comment by RachitKhattar** [comment]
Hi..
@crisnieto @mbelyaeva91 Did you get any solution for this? We are stuck with the same issue.

**Comment by mbelyaeva91** [comment]
@RachitKhattar Hi!
the only workaround i see is using coordinates of that specific element you wanna tap on driver.tap(fingers, x, y, duration);

**Comment by RachitKhattar** [comment]
@mbelyaeva91 thanks for a quick reply. Will try this approach, but since TableViews are supposed to be dynamic with their content, we wanted to automate it completely.

**Comment by crisnieto** [comment]
Hi @RachitKhattar 
Sadly no.. In my case, I don't think using coordinates is an scalable solution (this issue is present for every tableview on my software), so I had to move on and use another automation framework mainly because of this issue.

**Comment by edgy360** [comment]
Do the cells show within the server log (JSON) at the same time when they are missing from the XML? This will be really useful in helping to narrow down if the issue is our side or within the Appium server.

**Comment by tateexon** [comment]
I sadly have no solution for you all but I can report that I have been seeing the same behavior in appium for over a year. The tableview cells sometimes are accessible and other times they are not. I cannot find any trace of the cells in the logs when they are not present in the inspector. This has forced my testing in these areas to be manual :(

**Comment by crisnieto** [comment]
Hi @edgy360 
There is no trace of the elements in the server log when they are missing on the Inspector.

**Comment by edgy360** [comment]
Thanks both for checking this.

I believe that this is an issue from the main Appium project and Instruments side, but I will also perform some additional tests and then raise in the main project this evening.

**Comment by SrinivasanTarget** [comment]
@edgy360 I have many similar scenario's like Appium inspector doesn't recognise the elements (even instruments as well).How can we overcome such situations? App is built on xamarin as it is built on xamarin calabsh irb can able to list the elements always whereas our appium inspector list rarely.

@imurchie @penguinho I need your thoughts as well here.

Its about UIATableView contains many UIATableCells, inspector list UIATablecells rarely and it doesn't list the UIATableCells most of times. Appium server as well not able to recognise those elements found rarely by inspector.By this can i assume this as instruments bug? if so how inspector list the same sometimes.

**Comment by edgy360** [comment]
Thanks everyone for providing information on this.

I think that at this point we are going to need to hand this over to the main project to have a look, as we just display what is sent from Appium. If it doesn't show in the server logs then it's something from the Appium server side rather than us not displaying the information.

Please could someone who is expericing this issue raise it on the [main Appium issue tracker](https://github.com/appium/appium/issues) and then link back to here to link the issues? Thanks!

**Comment by sachin2788** [comment]
Hi All, 
I am  experiencing the same issue where UI elements inside UIATablecells not recognized and I am not finding in the image tabelcell or not get to any id. App is built  in xamarin @SrinivasanTarget  have you find any solution.
I am using
Appium 1.4.13 in iOS simulator.

**Comment by Lakhan0005** [comment]
Hi All,
I am experiencing the issue where i am unable to find a list of tabelcells .I am using Appium 1.4.13 please suggest what to do .Sometimes i am unable to find elements using Xpath. After Sometime same code works.Kindly Suggest what to do in Such Situations.

**Comment by JamieEdge** [comment]
appium-dot-app is no longer maintained. Please use appium-desktop instead.
