### ISSUE TITLE
Download is not getting completed on Mac - struck in the end

### ISSUE THREAD

**Issue by vikramvi** [appium/appium-dot-app#522]
https://bitbucket.org/appium/appium.app/downloads/

Tried downloading 1.4.13 twice , it never got completed ; got struck at 178 MB 0 sec

Kindly fix this issue

**Comment by brbrr** [comment]
same here. Using chrome

**Comment by pratana** [comment]
I had the same issue on Chrome

Try another browser instead. I ended up downloading it via Firefox.

**Comment by johnwanggithub** [comment]
+1. succeed by safari finally.

**Comment by Omurden** [comment]
+1, in chrome it's problematic, for safari, it's working.

**Comment by edgy360** [comment]
The same as https://github.com/appium/appium-dot-app/issues/525, which I just closed as I noticed it happens with other software (other than Appium).

Please reopen if this still occurs with the next release.

**Comment by vikramvi** [comment]
Works with FF as well.  

Only Chrome browser has issue downloading
