### ISSUE TITLE
Appium GUI doesn't list iOS 9 or 9+ simulators 

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium-dot-app#523]
Appium GUI doesnt list my iOS 9 or 9+ devices whereas isntruments -s devices list down iOS 9 simulators as well.
Appium GUI version: 1.4.13
<img width="1415" alt="screen shot 2015-12-16 at 8 55 15 pm" src="https://cloud.githubusercontent.com/assets/8896549/11862041/460e979a-a4ac-11e5-9edc-49ef2dd7d342.png">

**Comment by tplaza3** [comment]
I have the same issue. You can manually change the 8.x to 9.0 in order to use the iOS 9.0 simulators you have listed in your screenshot.

**Comment by SrinivasanTarget** [comment]
@tplaza3 Yup, aware of the workaround. Anyhow this needs to be fixed!
