### ISSUE TITLE
Cannot complete download for the GUI on El Capitan 

### ISSUE THREAD

**Issue by arpitabhayani** [appium/appium-dot-app#525]
The  download completes with 178MB  with 0sec left - however on the mac OSX 10.11.3 ( El Capitan) the download does not download the complete .dmg ( image) . I do not have slow WiFi. I downloaded via node and have been able to start up server successfully 
Thanks

**Comment by FilipUT** [comment]
I had the same issue when downloading with Chrome, but managed to download properly with Safari.

**Comment by nnniic** [comment]
@FilipUT  you are right.

**Comment by edgy360** [comment]
I noticed similar issues with other software (other than Appium) in Chrome. As mentioned by @FilipUT, it works in Safari, so it's not a problem with Appium that I can see.

Please reopen if this still occurs with the next release.
