### ISSUE TITLE
visible attribute is shown incorrectly in inspector

### ISSUE THREAD

**Issue by rompic** [appium/appium-dot-app#526]
I think
https://github.com/appium/appium-dot-app/blob/ef1d051ddeab736cad9bc10268a5c8e7bf766a47/Appium/Inspector/WebDriverElementNode.m#L210
should be changed to 
@"visible:", [NSString stringWithFormat:@" %@\n", (self._visible_ ? @"true" : @"false")]

see 
https://github.com/appium/appium-dot-app/blob/ef1d051ddeab736cad9bc10268a5c8e7bf766a47/Appium/Inspector/WebDriverElementNode.m#L103 where the visible element is set (and the clickable element doesn't seem to exist)

and the discussion in https://github.com/appium/appium/issues/6063

**Comment by williamrussell-grindr** [comment]
+1 for a fix!

**Comment by KateOgar** [comment]
+1 too

**Comment by edgy360** [comment]
This should be fixed in the next release.

**Comment by KateOgar** [comment]
but how i can check now that element is displayed on the screen? almost all the elements get visible=false and isDisplayed() method doesn't work now(

**Comment by edgy360** [comment]
You will need to ask in Appium Discuss for an answer to that question. This project is just the GUI which displays what Appium tells about the view.
