### ISSUE TITLE
Appium inspector giving blank screen for this page

### ISSUE THREAD

**Issue by mani9786** [appium/appium-dot-app#527]
Appium version (1.4.13) that exhibits the issue:
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: Mac 10.10.5 (14F27)
Mobile platform/version under test: 9.2 (Simulator and real devices )

682","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1752/8","x":0,"y":0,"width":254,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"Vet Housecall Practice","label":"Vet Housecall Practice","value":"Vet Housecall Practice","dom":null,"en
abled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1752/9","x":0,"y":0,"width":459,"height":21},">":[]}}]}},{"UIATableCell":{"@":{"name":"complete","label":null,"value":"","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1753","x":10,"y":131826,"width":748,"height":75},">":[{"UIAStaticText":{"@":{"name":"complete","label":"complete","value":"complete","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1753/0","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"02/26/2015","label":"02/26/2015","value":"02/26/2015","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1753/1","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"604.25","label":"604.25","value":"604.25","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1753/2","x":0,"y":0,"width":81,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"YES","label":"YES","value":"YES","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1753/3","x":0,"y":0,"width":30,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"0","label":"0","value":"0","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1753/4","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"3","label":"3","value":"3","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1753/5","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"111656978","label":"111656978","value":"111656978","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1753/6","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"1626 York Rd, TIMONIUM, MD, 21093","label":"1626 York Rd, TIMONIUM, MD, 21093","value":"1626 York Rd, TIMONIUM, MD, 21093","dom":null,"enabled":true,"valid":true,"visible":false,"hint":n
info: [debug] [INST] ull,"path":"/0/0/106/1753/7","x":0,"y":0,"width":413,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"NARC: 5673","label":"NARC: 5673","value":"NARC: 5673","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1753/8","x":0,"y":0,"width":254,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"Timonium Animal Hospital","label":"Timonium Animal Hospital","value":"Timonium Animal Hospital","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1753/9","x":0,"y":0,"width":459,"height":21},">":[]}}]}},{"UIATableCell":{"@":{"name":"complete","label":null,"value":"","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754","x":10,"y":131901,"width":748,"height":75},">":[{"UIAStaticText":{"@":{"name":"complete","label":"complete","value":"complete","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/0","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"02/26/2015","label":"02/26/2015","value":"02/26/2015","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/1","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"424.05","label":"424.05","value":"424.05","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/2","x":0,"y":0,"width":81,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"YES","label":"YES","value":"YES","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/3","x":0,"y":0,"width":30,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"0","label":"0","value":"0","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/4","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"3","label":"3","value":"3","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/5","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"022
615","label":"022615","value":"022615","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/6","x":0,"y":0,"width":180,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"111656692","label":"111656692","value":"111656692","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/7","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"17591 Frederick Rd, MOUNT AIRY, MD, 21771","label":"17591 Frederick Rd, MOUNT AIRY, MD, 21771","value":"17591 Frederick Rd, MOUNT AIRY, MD, 21771","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/8","x":0,"y":0,"width":413,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"NARC: 5513","label":"NARC: 5513","value":"NARC: 5513","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/9","x":0,"y":0,"width":254,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"Vetcor of Mt Airy, Country Vet","label":"Vetcor of Mt Airy, Country Vet","value":"Vetcor of Mt Airy, Country Vet","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1754/10","x":0,"y":0,"width":459,"height":21},">":[]}}]}},{"UIATableCell":{"@":{"name":"complete","label":null,"value":"","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755","x":10,"y":131976,"width":748,"height":75},">":[{"UIAStaticText":{"@":{"name":"complete","label":"complete","value":"complete","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755/0","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"02/26/2015","label":"02/26/2015","value":"02/26/2015","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755/1","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"400.79","label":"400.79","value":"400.79","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755/2","x":0,"y":0,"width":81,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"NO","label":"NO","value":"NO","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755/3","x":0,"y":0,"width":30,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"0","label":"0","value":"0","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755/4","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"4","label":"4","value":"4","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755/5","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"111656374","label":"111656374","value":"111656374","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755/6","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"112 Dry Mill Rd SW, LEESBURG, VA, 20175","label":"112 Dry Mill Rd SW, LEESBURG, VA, 20175","value":"112 Dry Mill Rd SW, LEESBURG, VA, 20175","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755/7","x":0,"y":0,"width":413,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"NARC: 13472","label":"NARC: 13472","value":"NARC: 13472","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755/8","x":0,"y":0,"width":254,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"Catoctin Veterinary Clinic,LLC","label":"Catoctin Veterinary Clinic,LLC","value":"Catoctin Veterinary Clinic,LLC","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1755/9","x":0,"y":0,"width":459,"height":21},">":[]}}]}},{"UIATableCell":{"@":{"name":"complete","label":null,"value":"","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1756","x":10,"y":132051,"width":748,"height":75},">":[{"UIAStaticText":{"@":{"name":"complete","label":"complete","value":"complete","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1756/0","x":0,"y":0,"wid
th":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"02/26/2015","label":"02/26/2015","value":"02/26/2015","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1756/1","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"2532.60","label":"2532.60","value":"2532.60","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1756/2","x":0,"y":0,"width":81,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"YES","label":"YES","value":"YES","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1756/3","x":0,"y":0,"width":30,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"0","label":"0","value":"0","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/106/1756/4","x":0,"y":0,"width":126,"height":21},">":[]}},{"UIAStaticText":{"@":{"name":"6","lab

![screen shot 2016-02-19 at 6 13 02 pm](https://cloud.githubusercontent.com/assets/17089075/13195086/55b7ba6e-d7ce-11e5-865b-0bd7792e76b0.png)
![screen shot 2016-02-19 at 10 12 45 pm](https://cloud.githubusercontent.com/assets/17089075/13195089/6415989c-d7ce-11e5-9b63-031ae3b595dd.png)

**Comment by edgy360** [comment]
Are you still facing this issue in the latest version of Appium? If so, please reopen this issue.

Additionally, please provide the output of 'Copy XML' (it's easier than server logs to read).
