### ISSUE TITLE
Cannot launch iOS App via GUI

### ISSUE THREAD

**Issue by JasonSmiley208** [appium/appium-dot-app#528]
When I run my code, everything works fine in Java.

However, when I want to view the app with the inspector (to fix my selectors), I get the following error:

> error: Could not pre-launch appium: Error: Instruments crashed on startup

Not sure why this is happening, but I noticed a warning also appearing in the logs:

> warn: Applications directory /Users/jason.smiley/Library/Developer/CoreSimulator/Devices/29E7EF7B-C0BF-404E-B87F-50083B9B1B11/data/Containers/Data/Application doesn't exist. Have you run this simulator before?

And this is appearing as well:

> 
> info: [debug] [INST STDERR] dyld: could not load inserted library '/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib' because no suitable image found.  Did find:
> 	/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib: mmap() error 1 at address=0x103B64000, size=0x00001000 segment=__TEXT in Segment::map() mapping /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib

This is my first time running the simulator, so not sure what I am missing. Please help!

----
I am running Appium on Mac OS 10.10.5

**Comment by edgy360** [comment]
This is a server error, rather than an issue with Appium.app, which is just the GUI that displays the server output. Please raise your issue here: https://github.com/appium/appium/issues

**Comment by JasonSmiley208** [comment]
I was able to fix this by adding the "--native-instruments-lib" flag. Not sure if this should be used by default?

**Comment by edgy360** [comment]
Thanks for advising this. I checked, and this flag is actually deprecated, so I would suggest still raising an issue over on the main project.

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
