### ISSUE TITLE
Windows 7 64 bit. Command prompt. Unable to load node configuration file to register with grid

### ISSUE THREAD

**Issue by Aznariy** [appium/appium-dot-app#530]
After successfully launching Selenium Grid on my http:\\localhost:4444\grid\console I'm unable to register any new node. After creating nodeconfig.json file and trying to execute this command **node.exe node_modules\appium\bin\appium.js --nodeconfig "C:\xxx\xxx\nodeconfig.json" -p 4723 -U d66d8f10** I'm getting further lines in my command prompt**:Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"udid":"d66d8f10","nodeconfig":"C:\\Aznariy Only\\Installed software\\GridConfiguration.json"}
info: Console LogLevel: debug
error: Unable to load node configuration file to register with grid**  Please can someone navigate me what exactly I'm doing wrong.

**Comment by edgy360** [comment]
Please raise your issue at: https://github.com/appium/appium/issues

This is the issue tracker for Appium.app, the OS X GUI.

**Comment by Aznariy** [comment]
@edgy360 Sorry for the wrong spot..

**Comment by edgy360** [comment]
No problem at all. :)
