### ISSUE TITLE
Developer Settings is not working with latest version of appium installed through npm

### ISSUE THREAD

**Issue by vikramvi** [appium/appium-dot-app#531]
As per Dan's webinar https://saucelabs.com/resources/webinars/10-things-you-didnt-know-about-appium ( 24:51 ) , I entered path of appium npm path.

Appium version 1.4.13 + Mac

Please look into this

But clicking on Launch button , server is not getting launched
![screen shot 2016-03-01 at 2 48 48 pm](https://cloud.githubusercontent.com/assets/308490/13428725/877391a4-dfbc-11e5-9484-a1ccfd5293e8.png)
![screen shot 2016-03-01 at 2 48 58 pm](https://cloud.githubusercontent.com/assets/308490/13428726/8774f83c-dfbc-11e5-814f-4f97050f71a3.png)

**Comment by priyankshah217** [comment]
@vikramvi , i think it tried to launch main.js from lib/server.
It should pick main.js from /usr/local/lib/node_modules/appium/build/lib/.

**Comment by vikramvi** [comment]
@priyankshah217 can you please clarify how to make that change ? I had referred to Dan's webinar and he didn't mention about changing / updating path of main.js

**Comment by vikramvi** [comment]
@penguinho can you please clarify if this is changed with 1.5 ?

**Comment by penguinho** [comment]
command line switches are no longer available in 1.5 which is why this doesn't work with 1.5. At some point in the next few weeks I'll update the app to work with 1.5, but unfortunately I'm quite busy at the moment

**Comment by vikramvi** [comment]
Thanks for clarification @penguinho . I will keep the ticket in open state. 
Kindly do the needful per your priorities.

**Comment by chrigrahcisco** [comment]
Additionally it's sending New Command Timeout as a string but it appears 1.5 requires integer.

`[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"9.2","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 6"},null,null,null,null,...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.2'
[Appium]   newCommandTimeout: '999999'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'iPhone 6'
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): newCommandTimeout must be of type number.`

**Comment by edgy360** [comment]
This is fixed in the next release of Appium.app (or if you run from source).
