### ISSUE TITLE
Please release .app for 1.5

### ISSUE THREAD

**Issue by scottdixon** [appium/appium-dot-app#532]
Appium 1.5 has been [released](https://discuss.appium.io/t/appium-1-5-0-released/8783).

This includes iOS 9.3 support.

**Comment by penguinho** [comment]
On my todo list, at some point I'll get around to this. Things have been crazy busy the last month.

**Comment by tomburns** [comment]
Any movement on this?

**Comment by williamrussellajb** [comment]
@penguinho I think the main reason for 1.5 app would be for the inspector. So many fixes in 1.5 that the old inspector doesn't have.

Is it possible to launch the inspector from command line? or the app only?

**Comment by williamrussell-grindr** [comment]
Okay, figured out how to get the inspector working... while running from source code.

**Comment by norekinc** [comment]
I've made some fixes on inspector that it works with remote appium 1.5.1 server for **my own use** and pushed to fork https://github.com/norekinc/appium-dot-app Feel free to use it. Bear in mind that changes include removing local Selenium framework and move it to Podfile, soo `pod install` is required before opening `Appium.xcworkspace`.
I've also created a branch https://github.com/norekinc/appium-dot-app/tree/pm-non-standalone-inspector that generally disables node + appium install on app startup, and hides all local-server-related items from the app.

p.s. I am not obj-c expert, so people may not like my changes ;)

**Comment by williamrussellajb** [comment]
@norekinc 
Both Apps for me always show that my elements are invisible.

This is the line that determines if it is visible or not. 

https://github.com/appium/appium-dot-app/blob/ef1d051ddeab736cad9bc10268a5c8e7bf766a47/Appium/Inspector/WebDriverElementNode.m#L224


Another problem I have, is that even if the element is "clickable" aka "visible", the inspector always shows "visible: false". If I dump the XML view, then I'm seeing the true value of the elements.

Any chance the Inspector can be fixed to show the same values as the XML dump?

**Comment by norekinc** [comment]
@williamrussellajb I would suggest to create separate issue for your problem, it's not related to the topic I think

**Comment by edgy360** [comment]
If I'm not mistaken, it's available here now: https://bitbucket.org/appium/appium.app/downloads/appium-1.5.2.dmg

I noticed however that the link on http://appium.io is pointing to the older version however.
