### ISSUE TITLE
Not able to download Appium APP

### ISSUE THREAD

**Issue by kapilsaxena** [appium/appium-dot-app#534]
When I try to download the appium app, it starts to download 178 MB of data but even after downloading full 178, it won't show it as completed.

Please see the following screenshot:
https://cloud.githubusercontent.com/assets/4608416/13984551/ed19504a-f11c-11e5-979b-ffe3c3884f8f.png

I am using Mac OS 10.11

**Comment by edgy360** [comment]
Please try another browser

**Comment by tomtom87** [comment]
Having the exactly same problem in all browsers including using wget and curl. I posted the issue here and was reffered here cannot download the dmg currently unable to obtain the software from anywhere and unable to use appium in the gui because of this

https://github.com/appium/appium/issues/6341#issuecomment-202500387

**Comment by GreenJeans** [comment]
I was able to workaround this pretty easily.

Cancel the download once it has apparently completed. Rename the file extension to ".dmg" and mount as normal.  Works fine!

**Comment by Astro03** [comment]
is this same issue still persisting?

**Comment by GreenJeans** [comment]
It didn't occur when I re-downloaded the 1.4.13 .app yesterday.

**Comment by gendelbendel** [comment]
I discovered that this issue only seemed to occur for me on Chrome. When using Safari, the file downloaded fine. This issue still occurs when downloading the most recent appium dmg, though the workaround (using Safari) still works.

**Comment by edgy360** [comment]
I've tested and the download worked ok in Chrome 50. There was a 20 second delay towards the end of the download, but the same (slightly shorter delay, but with a smaller file) happened for the Windows version too.

Please could you try this link? https://bitbucket.org/appium/appium.app/downloads/
