### ISSUE TITLE
for Appium test in android some elements method can not use in all API version??

### ISSUE THREAD

**Issue by kaku21** [appium/appium-dot-app#535]
I use appium version 1.4.6.1 for windows.and I use code [ WebElement el = driver.findElementById("com.example.android.contactmanager:id/addContactButton"); ] can run with the android simulator as API 19 level but it can not be worked in API 17.
on API 17 ,[ WebElement el = driver.findElement(By.xpath("//android.widget.Button[contains(@text,'Add Contact')]")); ] is worked.
I want to know is there some version specified???

**Comment by Astro03** [comment]
wrong channel.. open this in appium-dot-exe.. 

anywho.. why not rev to latest appium-dot-exe? have you tried that yet?
