### ISSUE TITLE
Appium 1.5.2 Inspector doesn't respect default command timeout

### ISSUE THREAD

**Issue by BJap** [appium/appium-dot-app#541]
Broken version (since): 1.5.2
Last working version: 1.4.13

User clicks start and server runs
User clicks inspect icon and device opens, then runs app
User does not send any new commands from the inspector window for 60 seconds

Expected behavior: App resumes and waits for commands (--command-timeout "99999")

Actual behavior: App closes and a logging test prints stating the following

```
[BaseDriver] Shutting down because we waited 60 seconds for a command

[debug] [AndroidDriver] Shutting down Android driver

[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
```

Startup logging:

```
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' build/lib/main.js --command-timeout "99999" --debug-log-spacing --automation-name "Appium" --platform-name "Android" --platform-version "5.0.1" --app "<some app>.apk" --avd "Nexus_5_API_21_x86" --app-wait-activity "<some activity>" --device-name "Android Emulator" --native-instruments-lib

[Appium] Welcome to Appium v1.5.2

[Appium] Non-default server args:

[Appium]   debugLogSpacing: true

[Appium]   defaultCommandTimeout: 99999
```

**Comment by edgy360** [comment]
This should be fixed in the next release. The issue was caused because of `--command-timeout` being deprecated. If you are using this outside of the Inspector, you should use the [`newCommandTimeout` capability](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md).

**Comment by mplachta** [comment]
When do you expect to release it?

**Comment by edgy360** [comment]
It will usually be done when the next Appium version is released. This isn't something I manage however, so I cannot tell for sure. If you need it urgently then I would recommend running from source for now.

**Comment by Astro03** [comment]
I'll release it when I get back into the country. So sometime in the beginning of June.  Sorry for your troubles.  

Ciao,
Astro
Sent from my phone

On May 19, 2016, at 19:12, Jamie Edge <notifications@github.com> wrote:

It will usually be done when the next Appium version is released. This isn't something I manage however, so I cannot tell for sure. If you need it urgently then I would recommend running from source for now.

**Comment by michaelgallacher** [comment]
Why doesn't this change appear in the documentation? I trust the docs, so it cost me a couple hours of debugging before I let go of that assumption.  To state the obvious, it's really painful to have the code and the docs out of sync.  When can we expect docs to be updated after a new release?

**Comment by edgy360** [comment]
If you have time to update the docs then that would be great, but I'm not sure what you want to be changed? The OS X project don't have any control over this command line arg change. As far as I see the UI setting works exactly the same as we describe.

It's worth watching the commit history on the main Appium branch for changes like this.

The main Appium.io has mentioned this new cap for some time, and it shows in the logs as a warning. That's how I realised what to fix on the GUI.

**Comment by pixyish** [comment]
I was running tap assistive touch using appium 1.4.16 on iOS. now we are getting issue in iOS 9.2 or above it is not launching assitive touch on tap using appium. so we try it from the latest appium version 1.5.2. but in the latest appium version we are getting issue session is not created. by running command my session creates for second and destroy immediately I am not able to tap/swipe without session error come instrument exit with code 0 and 
response comes from server side given below. but we did not get session.
please provide any solution for this.

running system command #5: /usr/local/Cellar/node/6.2.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/d9/8d6sp4653pv8xcm_xbl25dxc0000gn/T/instruments_sock 2,{"status":17,"value":"Can't find variable: error"}...
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.2","revision":"8ecfab8a598be15e7aa66e334b0ff92700943d1d"}}
[HTTP] <-- GET /wd/hub/status 200 235 ms - 121
