### ISSUE TITLE
iOS simulator closes with latest GUI 1.5.2 

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium-dot-app#550]
Hey folks,

I just downloaded the latest and when i try to inspect the application the iOS simulator launches and closes, that's it. Please refer the server logs 

https://gist.github.com/saikrishna321/a15a86356e82c41976b87d144cbbbc1b

**Comment by edgy360** [comment]
Hi Sai, unless you are using the Inspector, this is managed by Appium and not Appium.app (GUI). Please refer to [Appium Discuss](https://discuss.appium.io) and the [main Appium issue tracker](https://github.com/appium/appium/issues).

**Comment by saikrishna321** [comment]
@edgy360 i'm using the inspector and the simulator closes, when i run the tests starting the appium from commandline things go well. 

So this is something to do with Appium.app(GUI) it works fine for android, the inspector opens and i can inspect elements but not for iOS

**Comment by edgy360** [comment]
Ah, this might be due to the 'new command timeout' bug which I recently fixed. Please could you try running from source to see if this fixes your issue?

**Comment by saikrishna321** [comment]
@edgy360 i tried building from source and i still the issue refer the logs.. Any help 

https://gist.github.com/saikrishna321/a15a86356e82c41976b87d144cbbbc1b

**Comment by SrinivasanTarget** [comment]
@edgy360 Facing same issue w.r.t simulators

**Comment by edgy360** [comment]
Please can you try unchecking 'Use Native Instruments' from the iOS 'Advanced' tab and try again?

**Comment by saikrishna321** [comment]
@edgy360 its the same.. No luck ... 👎

**Comment by edgy360** [comment]
I’ve spent some more time looking into this, and I cannot replicate this even when I put the exact same arguments as in the provided logs. I’m not sure if I’m missing something.

The one difference is Xcode version. In the provided logs, they show Xcode 7.2.1. I’m using Xcode 7.3. Also, 9.2 Simulator compared to 9.3 that I’m using.

Please could you post your startup command line (first line in the logs) to compare? Mine under a working configuration is (with and without --pre-launch):

Launching Appium with command: ‘/Applications/Appium.app/Contents/Resources/node/bin/node' build/lib/main.js --session-override --pre-launch --debug-log-spacing --platform-version "9.3" --platform-name "iOS" --app "/Users/jamie/Development/Archive/Sample Projects/ScrollTest.app" --show-ios-log --device-name "iPhone 6s"

**Comment by saikrishna321** [comment]
Launching Appium with command: '/Users/saikrisv/Library/Developer/Xcode/DerivedData/Appium-agtmsofypijwttetzilxbpkwcshk/Build/Products/Debug/Appium.app/Contents/Resources/node/bin/node' build/lib/main.js --debug-log-spacing --log-level "debug" --platform-version "9.2" --platform-name "iOS" --app "/Users/saikrisv/Downloads/mob-0311052016.app.zip" --full-reset --show-ios-log --show-ios-log --device-name "iPhone 6" --language "en" --locale "en_US" --isolate-sim-device

**Comment by saikrishna321** [comment]
@edgy360 where can i set pre-launch option ?

**Comment by edgy360** [comment]
Please can you try turning off the 'full reset' option, and any other options so that the startup command matches mine?

The pre launch option is under the general settings.

**Comment by saikrishna321** [comment]
@edgy360 yeah it launches now .. 

```
Launching Appium with command: '/Users/saikrisv/Library/Developer/Xcode/DerivedData/Appium-agtmsofypijwttetzilxbpkwcshk/Build/Products/Debug/Appium.app/Contents/Resources/node/bin/node' build/lib/main.js --pre-launch --debug-log-spacing --log-level "debug" --platform-version "9.2" --platform-name "iOS" --app "/Users/saikrisv/Downloads/mob-0311052016.app.zip" --device-name "iPhone 6"
```
I don't see the elements on the Inspector screen refer the screenshot. 

![screen shot 2016-05-16 at 1 11 19 pm](https://cloud.githubusercontent.com/assets/4045041/15283372/91c852f2-1b67-11e6-8b05-0364efb8ebf0.png)

**Comment by saikrishna321** [comment]
@edgy360 any updates ?

**Comment by edgy360** [comment]
If it's launching then it was an issue with the arguments. Not something to do with the GUI.

Your other issue is due to your app leaving hidden elements visible to accessibility. It's not a fault in Appium.
