### ISSUE TITLE
Doctor broken in 1.5.2 

### ISSUE THREAD

**Issue by chrigrahcisco** [appium/appium-dot-app#552]
Noticed that Appium.app finally has an update to 1.5.2

Unfortunately the Doctor appear to be broken due to a missing file or bad path.

	'/Applications/Appium.app/Contents/Resources/node/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
		module.js:341
		    throw err;
		    ^

		Error: Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
		    at Function.Module._resolveFilename (module.js:339:15)
		    at Function.Module._load (module.js:290:25)
		    at Function.Module.runMain (module.js:447:10)
		    at startup (node.js:146:18)
		    at node.js:404:3

Contents of my /Applications/Appium.app/Contents/Resources/node_modules/appium/bin/

	drwxr-xr-x   3 chrigrah  admin   102 May 10 14:38 .
	drwxr-xr-x  26 chrigrah  admin   884 May 10 14:40 ..
	-rw-r--r--   1 chrigrah  admin  1708 May 10 14:38 ios-webkit-debug-proxy-launcher.js

**Comment by edgy360** [comment]
Thanks for raising this. I've applied a fix in #549 which should be in the next release. Please see #540 for the original issue.

For now it is best to install the doctor separately via npm, or compile the app from source (once merged).

**Comment by chrigrahcisco** [comment]
Thanks for investing time into Appium.app   I can now use the inspector directly from the .app instead of having to force breakpoints into a sacrificial testcase to allow inspection. :)

**Comment by edgy360** [comment]
No problem! I don't use the app with my job any more but still want to contribute and fix things, hence why I haven't had chance to commit anything for a few months. :)

**Comment by chandanch** [comment]
When I try to run Doctor I get the error as:

 Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

My Appium Version: 1.5.2(Acra)

I also installed appium-doctor via npm install -g appium-doctor and copy appium-docotor to /Applications/Appium.app/Contents/Resources/node_modules/appium/bin but did not work

**Comment by Nischalapp** [comment]
Issues with latest appium 1.5.2

**I have Xcode 7.2**

1. After downloading Latest Appium 1.5.2 and running the test simulator is getting crashed inbetween.

2. I am not able to install appium through terminal npm install appium - Installation happens properly but appium.js file is missing in /node_modules/appium/bin location. Not able to start appium. Only ios-webkit proxy file is there.

**Comment by gunesmes** [comment]
I have the same issue. Does downgrading solve the problem?

**Comment by edgy360** [comment]
A workaround is to use NPM to manually install the doctor until this fix is published.
