### ISSUE TITLE
Unable to get the package and launch activity in the Andriod Settings in Windows7 for Appium

### ISSUE THREAD

**Issue by sayom88** [appium/appium-dot-app#553]
![untitled](https://cloud.githubusercontent.com/assets/16284729/15185615/9a472c2c-17b7-11e6-9918-f47c26ddcd16.png)
Hello,
I am unable to get the package and launch activity in the Andriod Settings in Windows7 for Appium.
Can anyone help me here please.

**Comment by edgy360** [comment]
Hi, this is an issue with Appium.exe, so you will need to raise your issue within their project. This is the Mac app issue tracker.

https://github.com/appium/appium-dot-exe/issues
