### ISSUE TITLE
Unable to get the package and launch activity in the Andriod Settings in Windows7 for Appium

### ISSUE THREAD

**Issue by sayom88** [appium/appium-dot-app#554]
![untitled](https://cloud.githubusercontent.com/assets/16284729/15208167/b2eafbec-1847-11e6-835b-af453f5ebc86.png)
Hello,
I am unable to get the package and launch activity in the Andriod Settings in Windows7 for Appium.
Can anyone help how to get it please.

**Comment by edgy360** [comment]
Hi, as per https://github.com/appium/appium-dot-app/issues/553, this is an issue with Appium.exe, so you will need to raise your issue within their project. This is the Mac app issue tracker.

https://github.com/appium/appium-dot-exe/issues
