### ISSUE TITLE
Randomly the appium server crashed and never can't run test anymore.

### ISSUE THREAD

**Issue by littor** [appium/appium-dot-app#560]
Hi All,

I run app successfully many times with Appium server.
But sometimes, there will be crash, and after that, I can't launch and run test anymore. just like the server was destroyed.
The following is the log I got.

[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/nf/7b21_4qn6xd8lpgz79kc981m0000gn/T/appium-instruments/instrumentscli0.trace -w "iPad 2 (9.3)" /Users/my-QA/Apps/my.app -e UIASCRIPT "/Users/my-QA/Library/Application Support/appium/bootstrap/bootstrap-66f75f57865c78a5.js" -e UIARESULTSPATH /var/folders/nf/7b21_4qn6xd8lpgz79kc981m0000gn/T/appium-instruments'
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST STDERR] 2016-06-16 17:55:53.363 instruments[819:86501] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString hasPrefix:]: nil argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff88b804f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff872eef7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff88be74bd +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fff88acdd80 -[__NSCFString hasPrefix:] + 96
	4   InstrumentsPlugIn                   0x00000001038c1800 ___bestDeviceMatch_block_invoke + 502
	5   libdispatch.dylib                   0x00007fff8824f40b _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x00007fff882509f2 _dispatch_barrier_sync_f_invoke + 74
	7   InstrumentsPlugIn                   0x00000001038c15c4 _bestDeviceMatch + 233
	8   InstrumentsPlugIn                   0x00000001038c1a16 +[XRDeviceDiscovery devicesMatching:] + 57
	9   instruments                         0x0000000103572735 instruments + 10037
	10  instruments                         0x00000001035769ef instruments + 27119
	11  libdyld.dylib                       0x00007fff990a05ad start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

After I got this error, I can't run my test, whatever  test anymore.

Could you figure out what's the problem, it happened at my server, really make me very frustrated.

Thanks
Fox

**Comment by edgy360** [comment]
Hi there,

This error is within your app - not Appium:

[debug] [Instruments] [INST STDERR] 2016-06-16 17:55:53.363 instruments[819:86501] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString hasPrefix:]: nil argument’

‘Terminating app’ is because your app crashed, not Appium.

- Jamie

**Comment by littor** [comment]
Thanks, but the funny things is that, sometimes the test can be executed, and sometimes, it can't.
I will contact the dev to know what happened with the app.

**Comment by littor** [comment]
We have addressed the problem, why this problem happened is because of a bug of instrument.
I plugin my iPhone to the server for charging, and make it as untrusted the server.

And the problem happened. 

Thanks
Fox
