### ISSUE TITLE
appium.app doesn't provide response/feedback

### ISSUE THREAD

**Issue by reachbharathan** [appium/appium-dot-app#582]
I had installed the node, appium command line using npm install appium.
When i start appium using commandline i am able to run the test.
When i try to run the test by connecting through the appium.app [ui].
the app doesn't give any response in the console.
I had tried installing the app both by dmg as well as brew cask install both doesn't work
I tried unistalling the app and installing the app but even after that there was no response in the console.
I waited for the response maximum of half an hour but no response, but searched a lot still not able to find a solution for the same.
![appium app not responding](https://cloud.githubusercontent.com/assets/10195912/23336672/3e00a070-fba4-11e6-85dd-c26eb7c656e9.png)

appium app version: 1.5.3
appium version: 1.6.3
OSx version: 10.11.5

**Comment by jlipps** [comment]
this app is no longer supported. we're working on a new one, try to download one of the beta versions at https://github.com/appium/appium-desktop/releases
